= Beginning
// Ethereum initial development around the time of the yellowpaper, perhaps pre-software availability

Ethereum was first described by Vitalik Buterin in the _Ethereum White Paper_ <<ethereumwp>> at the end of 2013.

= Early History
// Ethereum through June-ish 2016

= Fork (Split of Ethereum and ETC)
// March-July 2016; events leading up to the fork through the fork

= Differences Between Ethereum and Ethereum Classic

== The EVM
For the most part (as of April 2018) the two networks remain highly compatible. Contract code produced for one chain runs as expected on the other. Though there are minimal differences in EVM OPCODES (noted in EIPs 140, 145, and 214).

== Core Network Development
All blockchains ultimately have many users and contributors, by core network development we mean the code that runs the network. In this case, due to the expertise and knowledge required, the bulk of development is often done by discrete groups. As such the code that these groups produce, and that actually runs on the network, is very closely tied together.

*Ethereum:* Ethereum Foundation, and volunteers.

*Ethereum Classic:* ETCDEV, IOHK, and volunteers.

== Ideological differences
One of the biggest material differences between Ethereum and Ethereum Classic is ideology which manifests itself in two key ways: immutability and community structure.

=== Immutability
Within the context of blockchains, immutability refers to preservation of blockchain history.

*Ethereum:* Follows a philosophy that's colloquially termed "governance". This philosophy allows participants to vote, with varying degrees of representation, to change the blockchain in certain cases (such as The DAO attack).

*Ethereum Classic:* Stands firmly behind the philosophy that once data is on the blockchain it cannot be modified by others. This is a philosophy shared with Bitcoin, Litecoin, and other cryptocurrencies.

=== Community structure
While blockchains aim to be decentralized much of the world around them is centralized. Ethereum and Ethereum Classic approach this fact in different ways.

*Ethereum:* The Ethereum Foundation owns the /r/ethereum subreddit, ethereum.org website, forums, GitHub (ethereum), Twitter (@ethereum), Facebook, and Google+ account. 

*Ethereum Classic:* Owned by separate entities: /r/ethereumclassic subreddit, ethereumclassic.org, forums, GitHubs (ethereumproject, ethereumclassic, etcdevteam, iohk, ethereumcommonwealth), Twitter (@eth_classic), Telegrams, and Discord.

= Other networks (forks in both blockchain and codebase)

[bibliography]
=== References
- [[[ethereumwp]]] 
*Original:* https://web.archive.org/web/20131228111141/http://vbuterin.com/ethereum.html
*Current:* https://github.com/ethereum/wiki/wiki/White-Paper