
== Ethereum Fork History

While some hard forks have always been planned as part of Ethereum's long term road map, these typically retain consensus after the fork. However there have been several forks throughout Ethereum's history that have either led to entirely distinct projects. In some cases such as Ethereum Classic (see below) this is due to communit consensis issues, but in others such as the launch of Expanse and others detailed below and it is to further differing development visions. In this next section we will detail a selection of the most notable hard forks in Ethereum's history that led to competing blockchains. 

=== Ethereum Classic (ETC)

Ethereum Classic came to be after Ethereum community went ahead with a time-sensitive controversial fork that split community consensus. On 20th July 2016 at a block height of 1920000 Ethereum introduced a state change via a hard-fork to protect approximately 3.6 million Ether that had been stolen from a prominent smart contract. A number of people in the community saw this as a violation of Ethereum's immutability and banded together to continue the original minority blockchain under the name Ethereum Classic. Initially the split was caused by a difference in ideologies and there were few minor technical differences. However that has changed over time with a series of hard forks adding or updating features and even introducing a fixed cap monetary policy of 210 million.

==== The genesis fork (Split of Ethereum and Ethereum Classic)

To understand why the fork that resulted in Ethereum Classic was controversial it is important to understand the context of its arrival. In the month before a project called "The DAO" launched as one of the first attempts at creating a truly decentralised organisation on the Ethereum blockchain. In it's sort lifespan it gathered over 11.5 Million Ether of investment, over $150 million USD at the time and attracted the attention of key players from across the ecosystem. Unfortunately there was a re-entrancy bug in one of the smart contracts which ultimately led to 3.6 Million Ether, approximately a third of it's assets, being drained by a malicious party. 

Due to protections built into this specific set of smart contracts, the funds were locked in a new address for 28 days. This meant the funds were isolated from the rest of the network and left a window open of opportunity for the community to take action. Several developers focused on finding a viable solution and many avenues were explored in a short space of time.  

Ultimately concluded that a hard fork would be the only realistic way to prevent the funds from being lost one way or another. The hard fork proposal was designed to trasfer all Ether that had been invested into the DAO smart contracts into a new smart contract which allowed the original owners of the Ether to claim a full refund. This provied a solution for returning the hacked funds but also meant interfering with the balances of specific addresses on the network however isolated they were. With time running out for this action to be viable multiple Ethereum development teams created clients that allowed a user to decide whether they wanted to enable this fork or not. 

To avoid developer bias on whether the hard fork wold be enabled or not, a voting toool was set up on the Ethereum blockchain itself. The vote took place over a 12 hour period closing at block height of 1894000. An interesting feature of this vote is that it was weigthed your Ether balance which meant that users with Ether locked in the The DAO smart contracts, arguable those with the most to gain, could not use the locked Ether towards the vote. Still the majority voted for the fork to go ahead. This meant that the default action would be to enable the hard fork unless a user had selected otherwise. 

The fork was scheduled and took place at block 1920000. When the forked version introducing the state change gained a majority of the mining power, many assumed that consensus had achieved and the minority chain would fade away as in previous forks. However some members of the community including one of the original co-founders, Charles Hoskinson, vocally supported the minority chain which came to be known as Ethereum Classic. Within days several exchanges began to list both versions of Ethereum. Due to the nature of hard forks all Ethereum users holding Ether at the time of the split now held funds on both of the chains and a market value was soon established. Some time later the stolen funds that initiated the debate were accessed and began to circulate on the Ethereum Classic chain.

===== Timeline of events leading up to the fork through the fork

Terms:

- DAO Attacker - An unknown person/entity that started attacking The DAO on June 17. Eventually taking ~3 million total Ether.
- Robinhood Group (RHG) - Lead by Jordi Baylina (jbaylina), this group secured the other ~7.2 million Ether.
- DAO Attack - The incident that lead to DAO funds being drained through the re-entrancy bug
- DAO Fork - The hard fork to reverse the effects of the DAO Attack

- April 5th: Slock.It creates The DAO following a security audit by Dejavu Security (https://blog.slock.it/deja-vu-dao-smart-contracts-audit-results-d26bc088e32e)
- April 30th: The DAO crowdsale launches (https://blog.slock.it/the-dao-creation-is-now-live-2270fd23affc)
- May 27: The DAO crowdsale ends
- June 9: A potential recursive call bug is discovered and believed to affect many Solidity contracts that track user's balances (http://vessenes.com/more-ethereum-attacks-race-to-empty-is-the-real-deal/)
- June 12: Stephen Tual declares that DAO funds are not at risk (https://blog.slock.it/no-dao-funds-at-risk-following-the-ethereum-smart-contract-recursive-call-bug-discovery-29f482d348b)
- June 17: The DAO is exploited and a variant of the recursive call bug (termed the "re-entry bug") is used to start draining the funds. (http://hackingdistributed.com/2016/06/18/analysis-of-the-dao-exploit/)
- June 21: The RHG is announces it has secured ~70% of the Ether stored within The DAO. The Attacker holds the other 30%. (https://www.reddit.com/r/ethereum/comments/4p7mhc/update_on_the_white_hat_attack/)
- June 24 2016: A soft fork vote is announced via opt-in signaling through Geth and Parity clients. This is designed to temporarily withhold funds until the community can better decide on what to do. (https://blog.ethereum.org/2016/06/24/dao-wars-youre-voice-soft-fork-dilemma/)
- June 28: A vulnerability is discovered in the soft fork and it's abandoned.(https://blog.ethereum.org/2016/06/28/security-alert-dos-vulnerability-in-the-soft-fork/)
- June 28 to July 15: Users debate on whether or not to hard fork. Most of the debate occurs on the /r/ethereum subreddit.
- July 15: The DAO Hard Fork is proposed to reverse The DAO Attack. (https://blog.slock.it/hard-fork-specification-24b889e70703)
- July 15: A vote is held on carbonvote to decide if the DAO Fork is opt-in (don't fork by default) or opt-out (fork by default) (https://blog.ethereum.org/2016/07/15/to-fork-or-not-to-fork/).
- July 15 - 20: 5.5% of the total Ether supply votes, ~80% of the votes (~4.5% of the total supply) are pro the opt-out hard fork. One quarter of the pro-DAO Fork vote comes from a single address.(https://elaineou.com/2016/07/18/stick-a-fork-in-ethereum/)
- July 20: The hard fork occurs at block 1,920,000. (https://blog.ethereum.org/2016/07/20/hard-fork-completed/ & https://etherscan.io/block/1920000)
- July 20: Those against the DAO Fork continue running the old non-hard fork client software. This leads to issues with transactions being replayed on both chains. (https://gastracker.io/block/0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f)
- July 24: Poloniex lists the original Ethereum chain under the ticker symbol ETC; the first exchange to do so. (https://twitter.com/poloniex/status/757068619234803712)
- August 10: The RHG transfers 2.9 million of the recovered ETC to Poloniex in order to convert it to ETH under the advice of Bity SA. 14% of the total RHG holdings are converted from ETC to ETH and other cryptocurrencies.(https://bitcoinmagazine.com/articles/millions-of-dollars-worth-of-etc-may-soon-be-dumped-on-the-market-1472567361/) 
- August 30: Poloniex subsequently freezes these funds and they're eventually sent back to the RHG. RHG then sets up a refund contract on the ETC chain. (https://medium.com/@jackfru1t/the-robin-hood-group-and-etc-bdc6a0c111c3 & https://www.reddit.com/r/EthereumClassic/comments/4xauca/follow_up_statement_on_the_etc_salvaged_from/)
- Jan 13, 2017: The ETC network is updated to resolve transaction replay issues. Both chains are now functionally separate.(https://www.reddit.com/r/EthereumClassic/comments/5nt4qm/diehard_etc_protocol_upgrade_successful_nethash/)

// Maybe mention dev team formation but not sure how crucial they are to the actual split; early members did contribute code for the fork that created the split, as well as ecosystem/infrastructure (gastracker.io, nodes, etc.) 
// IOHK - December 11, 2016 (https://ethereumclassic.github.io/blog/2016-12-12-TeamGrothendieck/)
// ETCDEV - February 20, 2017 (Need a source)


==== Technical differences 

===== The EVM
For the most part (as of April 2018) the two networks remain highly compatible. Contract code produced for one chain runs as expected on the other. Though there are minimal differences in EVM OPCODES (noted in EIPs 140, 145, and 214).

====== Core Network Development

All blockchains ultimately have many users and contributors, by core network development we mean the code that runs the network. In this case, due to the expertise and knowledge required, the bulk of development is often done by discrete groups. As such the code that these groups produce, and that actually runs on the network, is very closely tied together.

*Ethereum:* Ethereum Foundation, and volunteers.

*Ethereum Classic:* ETCDEV, IOHK, and volunteers.

==== Community differences

== Ideological differences
One of the biggest material differences between Ethereum and Ethereum Classic is ideology which manifests itself in two key ways: immutability and community structure.

===== Immutability
Within the context of blockchains, immutability refers to preservation of blockchain history.

*Ethereum:* Follows a philosophy that's colloquially termed "governance". This philosophy allows participants to vote, with varying degrees of representation, to change the blockchain in certain cases (such as The DAO attack).

*Ethereum Classic:* Stands firmly behind the philosophy that once data is on the blockchain it cannot be modified by others. This is a philosophy shared with Bitcoin, Litecoin, and other cryptocurrencies.

===== Community structure
While blockchains aim to be decentralized much of the world around them is centralized. Ethereum and Ethereum Classic approach this fact in different ways.

*Ethereum:* The Ethereum Foundation owns the /r/ethereum subreddit, ethereum.org website, forums, GitHub (ethereum), Twitter (@ethereum), Facebook, and Google+ account. 

*Ethereum Classic:* Owned by separate entities: /r/ethereumclassic subreddit, ethereumclassic.org, forums, GitHubs (ethereumproject, ethereumclassic, etcdevteam, iohk, ethereumcommonwealth), Twitter (@eth_classic), Telegrams, and Discord.


==== Ethereum Classic clients and tools

//// 
TODO: Add paragraph
////

=== A timeline of notable Ethereum forks

Several other non-consesus hard forks have already been launched and there will likely be more over the life of Ethereum. As they often share the same codebase it is important that replay protection is used when using the same address on the new chain and the original forked chain. This is because there is a risk of transactions being broadcast on both networks simulatneously with unintended consequences. 

- Expanse was the first fork of the Ethereum blockchain to gain traction. It was announced via the Bitcoion Talk forum on 7th of September 2015 and the actual fork occured a week later on 14th September 2015 at a block height of 800,000. It was originally founded by Christopher Franko and James Clayton. Their stated vision was to create an advanced chain for; "identity, governance, charity, commerce, and equity".
- Ethereum Classic officially began at block height of 1920001 on 20th July 2016 as the minority chain of an Ethereum fork. It's mission was to respect the principle of immutability for the original Ethereum blockchain by following the mantra that "Code is Law".
- EthereumFog (ETF) was launched on 14 December 2017 and forked at a block height of 4730660. Their stated aims are to develop "World Decentalized Fog Computing" by focusing on fog computing and decentralised storage. There is still little information on what this will actually entail.
- EtherInc (ETI) was launched on 13th February 2018 at a block height of 5078585 with a focus on building decentralised organisations. They also announced the reduction of block times, increased miner rewards, the removal of uncle rewards and set a cap on mineable coins. They use the same private keys as Ethereum and have implemented replay protection to protect Ether on the original unforked chain. 
- EtherZero (ETZ) was launched on 19th January 2018 at block height of 4936270 at a block height of 4936270. It's notable innovations were the introduction of a masternode architecture, instant transactions, and the removal of transaction fees for smart contracts to enable a wider diversity of DAPPs. There have been some criticism from some prominent members of the Ethereum community, MyEtherWallet and MetaMask, due to the lack of clarity surrounding development and some accusations of possible phishing. 

==== A note about token based forks

There are also several other projects that have been reported as or claim to be Ethereum forks, but are actually based on ERC20 tokens on the Ethereum network. Two apparent examples of these are EtherBTC (ETHB) and Ethereum Modification (EMOD). These are not forks in the traditional sense. 

[bibliography]
=== References
- [[[ethereumwp]]] 
*Original:* https://web.archive.org/web/20131228111141/http://vbuterin.com/ethereum.html
*Current:* https://github.com/ethereum/wiki/wiki/White-Paper