== Ethereum Fork History

While some hard forks have always been planned as part of Ethereum's long term road map, these typically retain consensus after the fork. However there have been several forks throughout Ethereum's history that have either led to entirely distinct projects. In some cases such as Ethereum Classic (see below) this is due to communit consensis issues, but in others such as the launch of Expanse and others detailed below and it is to further differing development visions. In this next section we will detail a selection of the most notable hard forks in Ethereum's history that led to competing blockchains. 

=== Ethereum Classic (ETC)

Ethereum Classic came to be after Ethereum community went ahead with a time-sensitive controversial fork that split community consensus. On 20th July 2016 at a block height of 1920000 Ethereum introduced a state change via a hard-fork to protect approximately 3.6 million Ether that had been stolen from a prominent smart contract. A number of people in the community saw this as a violation of Ethereum's immutability and banded together to continue the original minority blockchain under the name Ethereum Classic. Initially the split was caused by a difference in ideologies and there were few minor technical differences. However that has changed over time with a series of hard forks adding or updating features and even introducing a fixed cap monetary policy of 210 million.

==== The genesis fork

To understand why the fork that resulted in Ethereum Classic was controversial it is important to understand the context of its arrival. In the month before a project called "The DAO" launched as one of the first attempts at creating a truly decentralised organisation on the Ethereum blockchain. In it's sort lifespan it gathered over 11.5 Million Ether of investment, over $150 million USD at the time and attracted the attention of key players from across the ecosystem. Unfortunately there was a re-entrancy bug in one of the smart contracts which ultimately led to 3.6 Million Ether, approximately a third of it's assets, being drained by a malicious party. 

Due to protections built into this specific set of smart contracts, the funds were locked in a new address for 28 days. This meant the funds were isolated from the rest of the network and left a window open of opportunity for the community to take action. Several developers focused on finding a viable solution and many avenues were explored in a short space of time.  

Ultimately concluded that a hard fork would be the only realistic way to prevent the funds from being lost one way or another. The hard fork proposal was designed to trasfer all Ether that had been invested into the DAO smart contracts into a new smart contract which allowed the original owners of the Ether to claim a full refund. This provied a solution for returning the hacked funds but also meant interfering with the balances of specific addresses on the network however isolated they were. With time running out for this action to be viable multiple Ethereum development teams created clients that allowed a user to decide whether they wanted to enable this fork or not. 

To avoid developer bias on whether the hard fork wold be enabled or not, a voting toool was set up on the Ethereum blockchain itself. The vote took place over a 12 hour period closing at block height of 1894000. An interesting feature of this vote is that it was weigthed your Ether balance which meant that users with Ether locked in the The DAO smart contracts, arguable those with the most to gain, could not use the locked Ether towards the vote. Still the majority voted for the fork to go ahead. This meant that the default action would be to enable the hard fork unless a user had selected otherwise. 

The fork was scheduled and took place at block 1920000. When the forked version introducing the state change gained a majority of the mining power, many assumed that consensus had achieved and the minority chain would fade away as in previous forks. However some members of the community including one of the original co-founders, Charles Hoskinson, vocally supported the minority chain which came to be known as Ethereum Classic. Within days several exchanges began to list both versions of Ethereum. Due to the nature of hard forks all Ethereum users holding Ether at the time of the split now held funds on both of the chains and a market value was soon established. Some time later the stolen funds that initiated the debate were accessed and began to circulate on the Ethereum Classic chain.

==== Technical differences 

//// 
TODO: Add paragraph
////

==== Community differences

//// 
TODO: Add paragraph
////

==== Ethereum Classic clients and tools

//// 
TODO: Add paragraph
////

=== A timeline of notable Ethereum forks

Several other non-consesus hard forks have already been launched and there will likely be more over the life of Ethereum. As they often share the same codebase it is important that replay protection is used when using the same address on the new chain and the original forked chain. This is because there is a risk of transactions being broadcast on both networks simulatneously with unintended consequences. 

- Expanse was the first fork of the Ethereum blockchain to gain traction. It was announced via the Bitcoion Talk forum on 7th of September 2015 and the actual fork occured a week later on 14th September 2015 at a block height of 800,000. It was originally founded by Christopher Franko and James Clayton. Their stated vision was to create an advanced chain for; "identity, governance, charity, commerce, and equity".
- Ethereum Classic officially began at block height of 1920001 on 20th July 2016 as the minority chain of an Ethereum fork. It's mission was to respect the principle of immutability for the original Ethereum blockchain by following the mantra that "Code is Law".
- EthereumFog (ETF) was launched on 14 December 2017 and forked at a block height of 4730660. Their stated aims are to develop "World Decentalized Fog Computing" by focusing on fog computing and decentralised storage. There is still little information on what this will actually entail.
- EtherInc (ETI) was launched on 13th February 2018 at a block height of 5078585 with a focus on building decentralised organisations. They also announced the reduction of block times, increased miner rewards, the removal of uncle rewards and set a cap on mineable coins. They use the same private keys as Ethereum and have implemented replay protection to protect Ether on the original unforked chain. 
- EtherZero (ETZ) was launched on 19th January 2018 at block height of 4936270 at a block height of 4936270. It's notable innovations were the introduction of a masternode architecture, instant transactions, and the removal of transaction fees for smart contracts to enable a wider diversity of DAPPs. There have been some criticism from some prominent members of the Ethereum community, MyEtherWallet and MetaMask, due to the lack of clarity surrounding development and some accusations of possible phishing. 

==== A note about token based forks

There are also several other projects that have been reported as or claim to be Ethereum forks, but are actually based on ERC20 tokens on the Ethereum network. Two apparent examples of these are EtherBTC (ETHB) and Ethereum Modification (EMOD). These are not forks in the traditional sense. 
