= Beginning
[Ethereum initial development around the time of the yellowpaper, perhaps pre-software availability]

= Early History
[Ethereum through June-ish 2016]

= Fork (Split of Ethereum and ETC)
[March-July 2016; events leading up to the fork through the fork]

= Differences Between Ethereum and Ethereum Classic

== The EVM
For the most part (as of April 2018) the two networks remain highly compatible. Contract code produced for one chain runs as expected on the other. Though there are minimal differences in EVM OPCODES (noted in EIPs 140, 145, and 214).

== Core Network Development
All blockchains ultimately have many users and contributors, by core network development we mean the code that runs the network. In this case, due to the expertise and knowledge required, the bulk of development is often done by discrete groups.

*Ethereum:* Ethereum Foundation and volunteers.
*Ethereum Classic:* ETCDEV, IOHK, and volunteers.

== Ideological differences
One of the biggest material differences between Ethereum and Ethereum Classic is ideology which manifests itself in two key ways: immutability and community structure.

=== Immutability

=== Community structure

== Technical differences

= Other networks (forks in both blockchain and codebase)