////
Source: https://github.com/lrettig/ethereumbook/blob/develop/contrib/governance.asciidoc
License: CC0
Added by: @lrettig
////

:toc:

[[governance_chapter]]
== Ethereum governance

Understanding the technological mechanisms by which Ethereum accounts, transactions, and smart
contracts work is important, but equally important is understanding the human mechanisms by which
Ethereum was built and by which it continues to be developed. Ethereum is software, and Ethereum is
data (a ledger), but Ethereum is equally a community and a set of norms and processes governing the
interaction of the people in the community, and the interaction between the people and the system.
This set of norms and processes is Ethereum governance.

[[_anchor_governance_in_general]]
=== Governance in general

[quote]
Governance is the process by which people organize themselves to make decisions.

It may help to begin by defining governance. Simply put, governance is the process by which people
organize themselves to make decisions. Governance, on and off the blockchain, can take many forms.
It may be based on the authority of a single person (monarchy), of one or more deities (theology),
of experts (technocracy), of the people (democracy), or of money (plutarchy). While blockchain is a
radical new technology which enables new forms of governance (which we'll discuss in a moment),
ultimately blockchain governance is still old-fashioned governance: it's still people coming
together and putting in place norms and processes by which decisions will be made and carried out.

==== Some helpful terminology

Before going deeper into the topic of governance it may be helpful to lay out some useful
terminology and explain how it will be used throughout this chapter.

 * a *stakeholder* is a party affected by governance.
 * a *participant* is a party able to influence the governance process.
 * *legitimate* governance is governance in which there is common knowledge that the governance
 process will be used rather than abandoned or replaced
 * illegitimate
 * a stakeholder is *enfranchised* when they feel that a governance process produces decisions in
 their best interest.
 * a stakeholder is *disenfranchised* when they feel that a governance process produced decisions
 not in their best interest.
 * formalized, institutionalized
 * informal

==== Coordination problems

A coordination problem is any problem in which the decisions and strategy of one actor affect those
of other actors, and in which you, as an actor, cannot expect to achieve your desired outcome
without considering the decisions and strategy of the other actors.

Take, for example, the situation where my wife and I are both still at the office and both want to
meet at home and have dinner together.[1] If I head home but she stays at work, I'll be annoyed
because I will have wasted time and I can't work at home. In the same way, if she heads home but I
stay at work, she'll be annoyed. As you can see the outcome, and my utility, depend not only upon my
own actions but also upon her actions.

This is a simple, somewhat contrived example, but coordination problems are everywhere, from dating
to business to the job market to the stock market to international relations and wars. Voting is a
great, complex example of a coordination problem.

==== Game theory

==== Focal points

[[_anchor_blockchain_governance]]
=== Blockchain governance

==== Stakeholders

==== Off-chain governance

===== Case study: Bitcoin

==== On-chain governance

===== Case study: Tezos

===== Community and consensus

=== Ethereum governance today

==== Stakeholders

==== Process

==== EIPs

==== All core devs

==== The roadmap

==== Forks

=== The future of Ethereum governance

[[references_sec]]
=== References

[1] https://www.lesswrong.com/posts/yJfBzcDL9fBHJfZ6P/nash-equilibria-and-schelling-points
