== Scaling

One the most notable problems public blockchains face is scaling. According to Wikipedia, the definition of scaling in general can be "a computer's or network's ability to function as the number of users increases.". When talking about a blockchain, usage of the system is expressed in transactions. Based on that, we can define scalability in a blockchain as the ability of the network to function as the number of transactions increases. A popular way to measure scalability of a blockchain is measuring how much transactions per second (TPS) it can process.

////
Source: https://ethereum.stackexchange.com/a/49600/31518
License: CC-BY
Added by: @meshugah
////

Ethereum itself can support around 25 state updates (aka. transactions) per second, compared to around 500 transactions per second PayPal can support
or the millions state updates (tweets, comment, likes etc.) Twitter supports we can clearly see the problem, Ethereum can not support a massive adoption of users
without solving this problem. A great example of this would be the infamous Crypto Kitties flu of December 2017, it showed us exactly what a 
small pick in the usage of Ethereum can do to the network, transactions were taking hours to days and the fees were about 40 Gwei - 
more than 10 times higher than the typical fee.

=== "The Blockchain Trillema"

The reason for these scalability issues can be explained using what's called "The Blockchain Trillema".
This is a trillema where (without a decent solution) a blockchain can support only 2 edges of the triangle and needs to compromise on the on third one. 
The three edges are:

* Scalability
* Decentralization
* Security

We can look at what each combination of 2 out of the 3 may look like.

Scalability combined with Security - This could be a private blockchain, since the consensus needs to be achieved is only between a small cluster of trusted nodes (or maybe only one) 
there is no need for many security features public blockchains need and the communication between a few nodes is much faster than between a big decentralized network.

Scalability combined with Decentralization - A great example for that could be a public blockchain such as Bitcoin or Ethereum, but with neither 0 block confirmations
this may allow instant transactions with no fees but it is extremely insecure to the point it is just not useful for almost no use cases.

Decentralization and Security - this is certainly where most public blockchains including Bitcoin and Ethereum are at, they are decentralized and secure
but as said before, they do not support strong scaling solutions currently.

The problem with this Trillema is you can't completely win it, you just can't support very high TPS, have huge open network of nodes and be secure enough.

With that in mind, we can start exploring the different approaches of scaling the public blockchain without decreasing decentralization nor security
it is important to understand, since it is not possible to completely satisfy all the 3 at the same time most solutions aim to get to some point in the middle
where they have decent security, decentralization and scalability.

== Attempts at scaling

=== Casper - Proof of Stake for Ethereum
Proof of Stake is a relativly new type of consensus algorithm aims to improve/ replace the current Proof of Work consensus. The idea of Proof of Work consensus algoritm, in its simplest form, is to allow reaching consensus based on a 1 CPU 1 vote. Proof of Stake introduces a new voting power distribution idea in a 1 coin 1 vote basis.
Proof of Stake was designed to provide blockchain with finality, strengthen the economical security, reduce centralization risks and make the protocol better for the environment by removing the Proof of Work energy waste. Nevertheless, you should keep in mind this are the theoretically intended outcomes of the Proof of Stake consensus algorithm and there are potential drawbacks Proof of Stake can have.

Ethereum has decided to shift its consensus algorithm from Proof of Work to Proof of stake. The new Proof of Stake algoritm in Ethereum is called Casper - The Friendly GHOST. It was decided that the transition to Proof of Stake will be done in 2 phases. The first one is a hyberid Proof of Work - Proof of Stake algorithm called Casper the Friendly Finality Gadget (FFG) which aims to provide finality and implicitly reduce energy waste. The second implementation is called Casper Correct By Construction (CBC), this is a Proof of Stake only algorithm and will complete the Ethereum transition from Proof of Work to Proof of Stake.

Casper the Fiendly Finality Gadget (FFG)


Casper Correct by Construction (CBC)

Sharding 

Plasma 

Raiden 

Counterfactual State Channels 

Truebit

Loom Network
