== Scaling

One the most notable problems public blockchains face is scaling, 

TODO explain scaling generally

Ethereum itself can support around 15 state updates (aka. transactions) per second (TPS), compared to the 1000 transactions per second PayPal can support
or the millions state updates Twitter supports (tweets) we can clearly see the problem, Ethereum can not support a massive adoption of users
without solving this problem, a gre3at example of this would be the infamous Crypto Kitties flu of December 2017, it showed us exactly what a 
small pick in the usage of Ethereum can do to the network, transactions were taking hours to days and the fees were about 40 Gwei - 
more than 10 times higher than the typical fee.

=== "The Blockchain Trillema"

The reason for these scalability issues can be explained using what's called "The Blockchain Trillema".
This is a trillema where (without a decent solution) a blockchain can support only 2 edges of the triangle and needs to compromise on the on third one. 
The three edges are:

* Scalability
* Decentralization
* Security

We can look at what each combination of 2 out of the 3 may look like.

Scalability combined with Security - This could be a private blockchain, since the consensus needs to be achieved is only between a small cluster of trusted nodes (or maybe only one) 
there is no need for many security features public blockchains need and the communication between a few nodes is much faster than between a big decentralized network.

Scalability combined with Decentralization - A great example for that could be a public blockchain such as Bitcoin or Ethereum, but with neither 0 block confirmations
this may allow instant transactions with no fees but it is extremely insecure to the point it is just not useful for almost no use cases.

Decentralization and Security - this is certainly where most public blockchains including Bitcoin and Ethereum are at, they are decentralized and secure
but as said before, they do not support strong scaling solutions currently.

The problem with this Trillema is you can't completely win it, you just can't support very high TPS, have huge open network of nodes and be secure enough.

With that in mind, we can start exploring the different approaches of scaling the public blockchain without decreasing decentralization nor security
it is important to understand, since it is not possible to completely satisfy all the 3 at the same time most solutions aim to get to some point in the middle
where they have decent security, decentralization and scalability.

== Attempts at scaling

=== Casper - Proof of Stake for Ethereum
Proof of Stake as part of Casper is a relatively new consensus algorithm designed for Ethereum that has decided to split its shifting to Proof of Stake into to stages
one called the Casper FFG aka. Vitalik's Casper and the other called Casper the friendly GHOST aka. Casper CBC/ Vlad's Casper.
Casper FFG (the Fiendly Finality Gadget)

TODO: casper dif needs to be re-written


Casper CBC (Correct by Construction) aka. the friendly GHOST

Sharding 

Plasma 

Raiden 

Counterfactual State Channels 

Truebit

Loom Network
