[appendix]
[[ethereum_fork_history]]
== Ethereum Fork History
((("Ethereum (generally)","fork history", id="ix_appdx-forks-history-asciidoc0", range="startofrange")))((("forks", seealso="hard forks", id="ix_appdx-forks-history-asciidoc1", range="startofrange")))((("hard forks", id="ix_appdx-forks-history-asciidoc2", range="startofrange")))Most hard forks are planned as part of an upgrade roadmap and consist of updates that the community generally agrees to (i.e., there is social consensus). However, some hard forks lack consensus, which leads to multiple distinct blockchains. The events that led to the Ethereum/Ethereum Classic split are one such case, and are discussed in this appendix.

[[etc_origin]]
=== Ethereum Classic (ETC)
((("DAO (Decentralized Autonomous Organization)","and Ethereum Classic origins")))((("Ethereum Classic (ETC)","origins")))((("forks","ETC")))Ethereum Classic came to be after members of the Ethereum community implemented a time-sensitive hard fork (codenamed &#x201c;DAO&#x201d;). On July 20, 2016, at a block height of 1.92 million, Ethereum introduced an irregular state change via a hard fork in an effort to return approximately 3.6 million ether that had been taken from a smart contract known as The DAO. Almost everyone agreed that the ether taken had been stolen and that leaving it all in the hands of the thief would be of significant detriment to the development of the Ethereum ecosystem as well as the platform itself.

Returning the ether to its respective owners as though The DAO had never even existed was technically easy, if rather politically controversial. A number of people in the ecosystem disagreed with this change, believing immutability should be a fundamental principle of the Ethereum blockchain without exception; they elected to continue the original chain under the moniker of Ethereum Classic. While the split itself was initially ideological, the two chains have since evolved into separate entities.

[[dao_origin]]
=== The Decentralized Autonomous Organization (The DAO)

((("DAO (Decentralized Autonomous Organization)","about")))((("forks","DAO")))The ((("DAO (Decentralized Autonomous Organization)", id="ix_appdx-forks-history-asciidoc3", range="startofrange")))DAO was created by Slock.it, with the aim of providing community-based funding and governance for projects. The core idea was that proposals would be submitted, curators would manage proposals, funds would be raised from investors within the Ethereum community, and, if the projects proved successful, investors would receive a share of the profits.

The DAO was also one of the first experiments in an Ethereum token. Rather than funding projects directly with ether, participants would trade their ether for DAO tokens, use them to vote on project funding, and later be able to trade them back for ether. 

DAO tokens were available to purchase in a crowdsale that ran from April 5 through April 30, 2016, amassing https://www.economist.com/news/finance-and-economics/21699159-new-automated-investment-fund-has-attracted-stacks-digital-money-dao[nearly 14%] of the total ether in existence, which was worth ~$150 million at the time.

[[dao_reentrancy_bug]]
=== The Reentrancy Bug

((("forks","reentrancy bug")))((("reentrancy bug")))On June 9, 2016, developers Peter Vessenes and Chriseth reported that most Ethereum-based contracts that managed funds were potentially https://vessenes.com/more-ethereum-attacks-race-to-empty-is-the-real-deal/[vulnerable to an exploit] that could empty contract funds. A few days later, on June 12, Stephen Tual (cofounder of Slock.it) reported that https://blog.slock.it/no-dao-funds-at-risk-following-the-ethereum-smart-contract-recursive-call-bug-discovery-29f482d348b[The DAO's code was not vulnerable] to the bug described by Peter and Chriseth. Worried DAO contributors breathed a sigh of relief&#x2014;until five days later, when an unknown attacker started http://hackingdistributed.com/2016/06/18/analysis-of-the-dao-exploit[draining The DAO] using an exploit similar to the one for which the warning had been issued. Ultimately, the DAO attacker siphoned ~3.6 million ether out of The DAO.

Simultaneously, an assemblage of volunteers calling themselves the Robin Hood Group (RHG) started using the same exploit to withdraw the remaining funds in order to save them from being stolen by the DAO attacker. On June 21, https://www.reddit.com/r/ethereum/comments/4p7mhc/update_on_the_white_hat_attack/[the RHG announced] that they had secured about 70% of The DAO's funds (roughly 7.2 million ether), with plans to return it to the community (which they successfully did on the ETC network, and didn't need to do on the Ethereum network after the fork). Many thanks and commendations were given to the RHG for their quick thinking and fast actions that helped secure the bulk of the community's ether.

[[dao_reentrancy_bug_technicals]]
==== Technical Details
((("reentrancy bug","technical details")))While a more detailed and thorough explanation of the bug is given by http://hackingdistributed.com/2016/06/18/analysis-of-the-dao-exploit/[Phil Daian], the short explanation is that a crucial function in the DAO had two lines of code in the wrong order, meaning that the attacker could have requests to withdraw ether acted upon repeatedly, before the check of whether the attacker was entitled to the withdrawal was completed. This type of vulnerability is described in <<reentrancy_security>>.

[[dao_reentrancy_bug_attack_flow]]
==== Attack Flow
((("reentrancy bug","attack flow")))Imagine you had $100 in your bank account and you could bring your bank teller any number of withdrawal slips. The teller would give you money for each slip in order, and only after processing all the slips would they record your withdrawal. What if you brought them three slips, each requesting withdraw $100? What if you brought them three thousand?

The DAO attack worked like this:

1. The DAO attacker asks the DAO contract to withdraw DAO tokens (DAO).
2. The attacker asks the contract to withdraw DAO _again_, before the contract updates its records to show that DAO was withdrawn.
3. The attacker repeats step 2 as many times as possible.
4. The contract finally logs a single DAO withdrawal, losing track of the withdrawals that happened in the interim.

[[dao_hard_fork]]
=== The DAO Hard Fork
((("DAO (Decentralized Autonomous Organization)","hard fork", id="ix_appdx-forks-history-asciidoc4", range="startofrange")))((("forks","DAO", id="ix_appdx-forks-history-asciidoc5", range="startofrange")))((("hard forks", id="ix_appdx-forks-history-asciidoc6", range="startofrange")))Fortunately, there were several safeguards built into The DAO: notably, all withdrawal requests were subject to a 28-day delay. This gave the community a little while to discuss what to do about the exploit, because from roughly June 17&#x2013;July 20 the DAO attacker would be unable to convert their DAO tokens into ether.

Several developers focused on finding a viable solution, and multiple avenues were explored in this short space of time. Among them were a https://blog.ethereum.org/2016/06/24/dao-wars-youre-voice-soft-fork-dilemma/[_DAO soft fork_], announced on June 24, to delay DAO withdrawals until consensus was reached, and a https://blog.slock.it/hard-fork-specification-24b889e70703[_DAO hard fork_], announced on July 15, to reverse the effects of the DAO attack with an exceptional state change.

On June 28, developers discovered https://blog.ethereum.org/2016/06/28/security-alert-dos-vulnerability-in-the-soft-fork/[a DoS exploit in the DAO soft fork]  and concluded that the DAO hard fork would be the only viable option to fully resolve the situation. The DAO hard fork would transfer all ether that had been invested in The DAO into a new refund smart contract, allowing the original owners of the ether to claim full refunds. This provided a solution for returning the hacked funds, but also meant interfering with the balances of specific addresses on the network, however isolated they were. There would also be some leftover ether in portions of The DAO known as _childDAOs_. A group of trustees would manually authorize the leftover ether, worth https://elaineou.com/2016/07/18/stick-a-fork-in-ethereum/[~$6–7 million] at the time.

With time running out, multiple Ethereum development teams created clients that allowed a user to decide whether they wanted to enable this fork. However, the client creators wanted to decide whether to make this choice opt-in (don't fork by default) or opt-out (fork by default). On July 15, a vote was opened on https://blog.ethereum.org/2016/07/15/to-fork-or-not-to-fork/[_carbonvote.com_]. The next day, at block height https://etherscan.io/block/1894000[1,894,000], it was closed. Of the https://elaineou.com/2016/07/18/stick-a-fork-in-ethereum/[5.5% of the total ether supply] that voted, &#x7e;80% of the votes (&#x7e;4.5% of the total ether supply) voted for opt-out. One-quarter of the opt-out vote came from a single address.

Ultimately the decision became opt-out, so those who opposed the DAO hard fork would need to explicitly state their opposition by changing a configuration option in the software they were running.

On July 20, at block height https://etherscan.io/block/1920000[1,920,000], Ethereum https://blog.ethereum.org/2016/07/20/hard-fork-completed/[implemented the DAO hard fork] and thus two Ethereum networks were created: one including the state change, and the other ignoring it.

((("Ethereum Classic (ETC)","origins")))When the DAO hard-forked Ethereum (present-day Ethereum) gained a majority of the mining power, many assumed that consensus was achieved and the minority chain would fade away, as in previous forks. Despite this, a sizable portion of the Ethereum community (roughly 10% by value and mining power) started supporting the non-forked chain, which came to be known as Ethereum Classic.

Within days of the fork, several exchanges began to list both Ethereum ("ETH") and Ethereum Classic ("ETC"). Due to the nature of hard forks, all Ethereum users holding ether at the time of the split then held funds on both of the chains, and a market value for ETC was soon established with https://twitter.com/poloniex/status/757068619234803712[Poloniex] listing ETC on July 24.

[[dao_hard_fork_timeline]]
==== Timeline of the DAO Hard Fork

- April 5, 2016: Slock.it https://blog.slock.it/deja-vu-dao-smart-contracts-audit-results-d26bc088e32e[creates The DAO] following a security audit by Dejavu Security.
- April 30, 2016: The DAO crowdsale https://blog.slock.it/the-dao-creation-is-now-live-2270fd23affc[launches].
- May 27, 2016: The DAO crowdsale ends.
- June 9, 2016: A generic https://vessenes.com/more-ethereum-attacks-race-to-empty-is-the-real-deal/[recursive call bug] is discovered and believed to affect many Solidity contracts that track users' balances.
- June 12, 2016: Stephen Tual https://blog.slock.it/no-dao-funds-at-risk-following-the-ethereum-smart-contract-recursive-call-bug-discovery-29f482d348b[declares] that The DAO's funds are not at risk.
- June 17, 2016: http://hackingdistributed.com/2016/06/18/analysis-of-the-dao-exploit/[The DAO is exploited] and a variant of the discovered bug (termed the "reentrancy bug") is used to start draining the funds, eventually nabbing ~30% of the ether.
- June 21, 2016: The RHG https://www.reddit.com/r/ethereum/comments/4p7mhc/update_on_the_white_hat_attack/[announces] it has secured the other ~70% of the ether stored within The DAO.
- June 24, 2016: A https://blog.ethereum.org/2016/06/24/dao-wars-youre-voice-soft-fork-dilemma/[soft fork vote] is announced via opt-in signaling through Geth and Parity clients, designed to temporarily withhold funds until the community can better decide what to do.
- June 28, 2016: A https://blog.ethereum.org/2016/06/28/security-alert-dos-vulnerability-in-the-soft-fork/[vulnerability] is discovered in the soft fork and it's abandoned.
- June 28, 2016 to July 15: Users debate whether or not to hard fork; most of the vocal public debate occurs on the _/r/ethereum_ subreddit.
- July 15, 2016: The https://blog.slock.it/no-dao-funds-at-risk-following-the-ethereum-smart-contract-recursive-call-bug-discovery-29f482d348b[DAO hard fork] is proposed, to return the funds taken in the DAO attack.
- July 15, 2016: A https://blog.ethereum.org/2016/07/15/to-fork-or-not-to-fork/[vote is held] on CarbonVote to decide if the DAO hard fork will be opt-in (don't fork by default) or opt-out (fork by default).
- July 16, 2016: https://elaineou.com/2016/07/18/stick-a-fork-in-ethereum/[5.5% of the total ether supply votes]; pass:[~80% of the votes (~4.5%] of the total supply) are pro the opt-out hard fork, with one-quarter of the pro-vote coming from a single address.
- July 20, 2016: The https://blog.ethereum.org/2016/07/20/hard-fork-completed/[hard fork] occurs at block 1,920,000.
- July 20, 2016: Those against the DAO hard fork continue running the old client software; this leads to issues with https://www.coindesk.com/rise-replay-attacks-ethereum-divide/[transactions being replayed on both chains].
- July 24, 2016: https://twitter.com/poloniex/status/757068619234803712[Poloniex lists] the original Ethereum chain under the ticker symbol ETC; it's the first exchange to do so.
- August 10, 2016: The RHG https://medium.com/@jackfru1t/the-robin-hood-group-and-etc-bdc6a0c111c3[transfers 2.9] million of the recovered ETC to Poloniex in order to convert it to ETH on the advice of Bity SA; 14% of the total RHG holdings are converted from ETC to ETH and other cryptocurrencies, and https://bitcoinmagazine.com/articles/millions-of-dollars-worth-of-etc-may-soon-be-dumped-on-the-market-1472567361/[Poloniex freezes] the other 86% of deposited ETH.
- August 30, 2016: The frozen funds are sent by Poloniex back to the RHG, which then sets up a refund contract on the ETC chain.
- December 11, 2016: IOHK's ETC development team forms, led by Ethereum founding member Charles Hoskinson.
- January 13, 2017: The ETC network is updated to resolve transaction replay issues; the chains are now functionally separate.
- February 20, 2017: The ETCDEVTeam forms, led by early ETC developer Igor Artamonov(((range="endofrange", startref="ix_appdx-forks-history-asciidoc6"))) (splix).(((range="endofrange", startref="ix_appdx-forks-history-asciidoc5")))(((range="endofrange", startref="ix_appdx-forks-history-asciidoc4")))(((range="endofrange", startref="ix_appdx-forks-history-asciidoc3")))

[[eth_etc_differences]]
=== Ethereum and Ethereum Classic

((("Ethereum (generally)","Ethereum Classic compared to")))((("Ethereum Classic (ETC)","Ethereum compared to")))((("forks","ETC")))((("forks","Ethereum and Ethereum Classic split")))While the initial split was centered around The DAO, the two networks, Ethereum and Ethereum Classic, are now separate projects, although most development is still done by the Ethereum community and simply ported to Ethereum Classic codebases. Nevertheless, the full set of differences is constantly evolving and too extensive to cover in this chapter. However, it is worth noting that the chains do differ significantly in their core development and community structure. A few of the technical differences are discussed next.


[[eth_etc_differences_evm]]
==== The EVM
((("EVM OPCODES")))For the most part (at the time of writing), the two networks remain highly compatible: contract code produced for one chain runs as expected on the other; but there are some small differences in EVM OPCODES (see EIPs link:https://github.com/ethereum/EIPs/blob/master/EIPS/eip-140.md[140], link:https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md[145], and link:https://github.com/ethereum/EIPs/blob/master/EIPS/eip-214.md[214]).

[[eth_etc_differences_core_development]]
==== Core Network Development
Being open projects, blockchain platforms often have many users and contributors. However, the core network development (i.e., of the code that runs the network) is often done by small groups due to the expertise and knowledge required to develop this type of software. On Ethereum, this work is done by the Ethereum Foundation and volunteers. On Ethereum Classic, it's done by ETCDEV, IOHK, and volunteers.

[[ethereum_forks]]
=== Other Notable Ethereum Forks

((("Ellaism")))https://ellaism.org/about/[Ellaism] is an Ethereum-based network that intends to use PoW exclusively to secure the blockchain. It has no pre-mine and no mandatory developer fees, with all support and development donated freely by the community. Its developers believe this makes theirs &#x201c;one of the most honest pure Ethereum projects,&#x201d; and one that is &#x201c;uniquely interesting as a platform for serious developers, educators, and enthusiasts. Ellaism is a pure smart contract platform. Its goal is to create a smart contract platform that is both fair and trustworthy.&#x201d; The principles of the platform are as follows:

____
* All changes and upgrades to the protocol should strive to maintain and reinforce these Principles of Ellaism.
* Monetary Policy: 280 million coins.
* No Censorship: Nobody should be able to prevent valid txs from being confirmed.
* Open-Source: Ellaism source code should always be open for anyone to read, modify, copy, share.
* Permissionless: No arbitrary gatekeepers should ever prevent anybody from being part of the network (user, node, miner, etc).
* Pseudonymous: No ID should be required to own, use Ellaism.
* Fungible: All coins are equal and should be equally spendable.
* Irreversible Transactions: Confirmed blocks should be set in stone. Blockchain History should be immutable.
* No Contentious Hard Forks: Never hard fork without consensus from the whole community. Only break the existing consensus when necessary.
* Many feature upgrades can be carried out without a hard fork, such as improving the performance of the EVM.
____

Several other forks have occurred on Ethereum as well. Some of these are hard forks, in the sense that they split directly off of the preexisting Ethereum network. Others are software forks: they use Ethereum's client/node software but run entirely separate networks without any history shared with Ethereum. There will likely be more forks over the life of Ethereum.

There are also several other projects that claim to be Ethereum forks but are actually based on ERC20 tokens and run on the Ethereum network. ((("airdrops")))((("EMOD (Ethereum Modification)")))((("ETHB (EtherBTC)")))((("EtherBTC (ETHB)")))((("Ethereum Modification (EMOD)")))Two examples of these are EtherBTC (ETHB) and Ethereum Modification (EMOD). These are not forks in the traditional sense, and may sometimes be called &#x201c;airdrops.&#x201d;

Here's a brief rundown of some of the more notable forks that have occurred:

- ((("Expanse")))_Expanse_ was the first fork of the Ethereum blockchain to gain traction. It was announced via the Bitcoin Talk forum on September 7, 2015. The actual fork occurred a week later on September 14, 2015, at a block height of 800,000. ((("Clayton, James")))((("Franko, Christopher")))It was originally founded by Christopher Franko and James Clayton. Their stated vision was to create an advanced chain for: "identity, governance, charity, commerce, and equity".
- ((("ETF (EthereumFog)")))((("EthereumFog (ETF)")))_EthereumFog_ (ETF) was launched on December 14, 2017, and forked at a block height of 4,730,660. The project's stated aim is to develop "world decentralized fog computing" by focusing on fog computing and decentralized storage. There is still little information on what this will actually entail.
- _EtherZero_ (ETZ) ((("EtherZero (ETZ)")))was launched on January 19, 2018, at a block height of 4,936,270. Its notable innovations were the introduction of a masternode architecture and the removal of transaction fees for smart contracts to enable a wider diversity of DApps. There has been some criticism from some prominent members of the Ethereum community, MyEtherWallet, and MetaMask, due to the lack of clarity surrounding development and some accusations of possible phishing.
- ((("EtherInc (ETI)")))((("ETI (EtherInc)")))_EtherInc_ (ETI) was launched on February 13, 2018, at a block height of 5,078,585, with a focus on building decentralized organizations. Stated goals include the reduction of block times, increased miner rewards, the removal of uncle rewards, and setting a cap on mineable coins. EtherInc uses the same private keys as Ethereum and has implemented replay protection to protect ether on the original non-forked chain.(((range="endofrange", startref="ix_appdx-forks-history-asciidoc2")))(((range="endofrange", startref="ix_appdx-forks-history-asciidoc1")))(((range="endofrange", startref="ix_appdx-forks-history-asciidoc0")))

