[Consensus]

== What's Consensus

=== What's POW

=== What's POS

=== What's DPOS (optional)

== Consensus Of Ethereum

=== Introduction Of Ethash

Ethash is an Ethereum Proof of Work (PoW) algorithm *PoW algorithm* that is dependent on the generation of the initial epoch of a dataset that is approximately 1GB in size known as the Directed Acyclic Graph (*DAG*). The *DAG* uses a version of the *Dagger-Hashimoto Algorithm*, which is a combination of *Vitalik Buterin's Dagger algorithm* and *Thaddeus Dryja's Hashimoto algorithm*. The *Dagger-Hashimoto Algorithm* is the mining algorithm used by Ethereum 1.0. Over time the *DAG* grows linearly and is updated once every *epoch* (30,000 blocks, 100 hours).

==== Seed, Cache, Data Generation

The *PoW algorithm* involves:
- *Seed* is computed for each block by scanning through prior block headers of the *DAG*.
- *Cache* is a 16MB pseudorandom cache that is computed from the seed for storage in Light Clients
- *Data Generation* of the *DAG* from the cache to use for storage on Full Clients and Miners (where each item in the dataset only depends on a small number of items from the cache). 
- Miners undertake mining by taking random slices of the dataset and hashing them together. Verification may be performed using the stored cache and low memory to regenerate specific pieces of the dataset required.

.References:
- Ethash-DAG; https://github.com/ethereum/wiki/wiki/Ethash-DAG
- Ethash Specification; https://github.com/ethereum/wiki/wiki/Ethash
- Mining Ethash DAG; https://github.com/ethereum/wiki/wiki/Mining#ethash-dag
- Dagger-Hashimoto Algorithm; https://github.com/ethereum/wiki/blob/master/Dagger-Hashimoto.md
- DAG Explanation and Images; https://ethereum.stackexchange.com/questions/1993/what-actually-is-a-dag
- Ethash in Ethereum Yellowpaper; https://ethereum.github.io/yellowpaper/paper.pdf#appendix.J
- Ethash C API Example Usage; https://github.com/ethereum/wiki/wiki/Ethash-C-API

==== POW Function 

==== Why GPU Does Matter ?


=== Introduction Of Casper 

==== POS

==== Slash Protocol






