[[decentralized_applications_chap]]
== Decentralized Applications (DApps)

The peer-to-peer movement has enabled millions of Internet users to connect. +USENET+, a distributed messaging system that is described as the first peer-to-peer architecture, was established in 1979. It was built as an alternative and complement to the first 'Internet', +ARPANET+. +ARPANET+ was a client–server network where participants ran nodes requesting and serving content, but, as it lacked the ability to provide any means for context beyond simple address-based routing, +USENET+ emerged, promising a decentralized model of control. The +USENET+ model was a client–server model from the user perspective, but offered a self-organizing approach to the newsgroup servers. This made news servers communicate with one another as peers to propagate +USENET+ news articles over the entire group of network servers. This is also like SMTP email, in which the core e-mail-relaying network of mail transfer agents has a peer-to-peer character, in contrast to the periphery of e-mail clients and their direct connections which is strictly a client–server relationship.

In 1999 the famous music- and file-sharing application called Napster arose. Napster was the beginning of the peer-to-peer networks movement, evolving into BitTorrent, where participating users established a virtual network with no intrinsic authorities or other administrative restrictions.

As peer-to-peer mechanisms can be used to access any kind of distributed resources, they play a central role in decentralized applications.

////
Source: https://en.wikipedia.org/wiki/Peer-to-peer
License: CC0
Added by: @dcoldeira
////

[[what_is_a_dapp_sec]]
=== What is a DApp?

Unlike a traditional software application, a Decentralized Application (DApp) is not offered by a single provider or server. Instead, the whole stack is deployed and operated in a distributed fashion on a peer-to-peer (P2P) network.

A typical DApp stack consists of front-end, back-end and data storage. There are many advantages to a DApp compared to a centralized architecture:

1. Resiliency: by having the business logic controlled by a smart contract, a DApp back-end will be fully distributed over a blockchain platform, will not suffer downtime, and will continue to be available for as long as the platform is still operating.

2. Transparency: the on-chain nature of a DApp allows everyone to inspect the code and see how it works. Similarly, all interactions with the the DApp will be stored forever in the blockchain state history.

3. Censorship Resistance: as long as a user has access to an Ethereum node (running one if necessary), the user will always be able to interact with a DApp without interference. No service provider, even the owner of the smart contract, can alter the code once it is deployed on the network.

It is worth noting that, once deployed, a smart contract becomes publicly viewable, so anyone can take the contract's bytecode and re-deploy it themselves. This makes developing successful business models that depend on clever coding tricks hard on blockchain platforms; but the advantages of such platforms more than compensate in many cases.

It is also worth noting that understanding compiled bytecode, even using tools such as decompilers, can be tricky. To make their contracts' behavior fully transparent, developers should publish the source code for users to read, compile and verify.


[[components_of_a_dapp_sec]]
=== Components of a DApp

A DApp comprises several key components:

* Decentralized (i.e. on-chain) computation, related state, and value transfer, aka smart contracts
* Decentralized data storage, such as IPFS or Swarm
* Decentralized messaging, such as Whisper
* User front-end interface(s), usually written in the same languages as web interfaces and rendered in a web browser

In the Ethereum ecosystem as it stands today, there are very few truly decentralized apps - most still rely on centralized service and servers for some part of their operation. For example, the storage of front-end assets on servers owned and operated by the developer, or the provision of "real-world" information, such as the current price of ether. In the future, we expect that it will be possible for every part of any DApp to be operated in a truly and fully decentralized way, including access to "real world" data, such as prices or weather data. Data providers in our blockchain context are called "oracles" and their implementation poses a not insignificant challenge to the move to decentralization. Nevertheless, we are already on the way with the launch of Oraclize and other similar oracle services. We discussed oracles in <<oracles_chap>>.

[[blockchain_smart_contracts_sec]]
==== On-chain Computation (Smart Contracts)

The smart contract is used to store the business logic (program code) and the related state of your decentralized application; in the first instance, you can think of a smart contract as a server-side component in a regular application. One of the main differences is that any computation executed in a smart contract is very expensive and so should be kept to a minimum.

The design of Ethereum DApp architectures can go well beyond simple decision tree logic: Ethereum smart contracts allow you to build almost arbitrarily complex architectures in which a network of smart contracts call and pass data between each other, reading and writing their own state variables as they go. We have to add "almost" in our description, because the amount of computation that can be done in one atomic unit (transaction) will always be limited to some degree, as specified by the (possibly very large) block gas limit. Once you deploy your smart contract, your business logic could well be used by many other developers in the future, without any effort on your part!

A major consideration of smart contract design is the inability to change the code of a smart contract once it is deployed. It can be deleted if it is programmed with an accessible +SELFDESTRUCT+ opcode, but other than complete removal the code cannot be changed in any way. One reason why the Ethereum platform is designed this way is to maximize the degree to which users can know what smart contract–based services will do; it would undermine this to allow smart contract code to be changed in any way after creation. For example, a contract owner could write a contract that accepts ether deposits which will be returned in full after a fixed period of time, then wait until someone issues a transaction to deposit a large amount and change the code to allow them to withdraw the whole deposit for themselves. This is clearly a wholly undesirable feature for an otherwise immutable smart contract platform.

Nevertheless, it is possible for one smart contract to call another specified by a state variable. If the variable is changed, a different contract is called, which gives a maintenance and upgrade path for DApps. You may wonder, after thinking about the malign example above, why anyone would ever use a contract that they can see allows for parts of its operation to be changed; the reason is that one can always see how and to what extent a given contract allows possible code changes. For example, a DApp might make contract call address changes only after being approved by a special council or user vote, or they can be designed to separate computation from ether spending, so that the transfer of any deposit you have given it always needs your approval (and the code to ensure this is fixed). Great care is needed when employing this strategy, but it is very powerful.

The second major consideration of smart contract architecture is DApp size; a really large monolithic smart contract may cost a lot of gas to deploy and use. Therefore, some applications may choose to have off chain computation and an external data source. Keep in mind, however, that having the core business logic of the DApp be dependent on external data (e.g. from a centralized server) would mean your users will have to trust these externalities. The effort needed to gain this trust could end up being more costly than paying for on-chain resources: an interesting trade-off.

[[front_end_web_ui_cec]]
==== Front end (Web User Interface (UI))

Unlike the business logic of the DApp, which requires a developer who understands the EVM and new languages such as Solidity, the client side interface of a DApp can use basic web front end technologies (HTML, CSS, JavaScript, etc). This allows a traditional web developer to use familiar tools, libraries and frameworks. Interactions with the DApp such as signing messages, sending transactions and key management are often conducted through the browser itself, using tools such as the Mist browser or the MetaMask browser extension.

Although it is possible to create mobile DApps, currently there are few resources to help create mobile DApp front-ends, mainly due to the lack of mobile clients that can serve as a light client with key management functionality.

[[data_storage_sec]]
==== Data storage

Due to high gas costs and the currently low block gas limit, smart contracts are not suited to store or process large amounts of data. Hence, most DApps will use off-chain data storage services, ideally on decentralized platforms such as IPFS or Swarm. This is ideal for storing and distributing large static assets such as images, videos, and the rest of the client side application (HTML, CSS, JavaScript, etc).

Decentralized storage platforms work by using hashes of the file contents as file handles for reference and retrieval. The hashes of the content (or derivatives thereof) are often stored as bytes within the smart contract so that a user can be sure they are being served the correct content.


[[on_chain_vs_off_chain_data_sec]]
===== On-chain vs. off-chain

////
TODO: add paragraph
////

[[ipfs_sec]]
===== IPFS

////
TODO: add paragraph
////

[[swarm_sec]]
===== Swarm

Swarm is a decentralized data dissemination protocol.

* Home page: http://swarm-gateways.net/bzz:/theswarm.eth/
* Documentation: https://swarm-guide.readthedocs.io/en/latest/index.html
* Developer's onboarding guide: https://github.com/ethersphere/swarm/wiki/swarm
* The swarm engine room: https://gitter.im/ethersphere/orange-lounge
* Comparison between Swarm and IPFS: https://github.com/ethersphere/go-ethereum/wiki/IPFS-&-SWARM

[[centralized_db_sec]]
===== Centralized databases

Centralized databases store data indexed for fast retrieval, on a server with a single access point. They use a client–server network architecture and can allow users to modify stored data. Access control (e.g. read and write privileges) and the coordination of data changes by users is much easier than in a decentralized context. However, the centralization of control means that attackers can access and control the data with potentially simple and inexpensive techniques, such as social engineering.

////
Source:
https://dcoldeira.github.io/database-the-decentralized-control-revolution.html
License: CC0
Added by: @dcoldeira
////

[[oracle_sec]]
===== Oracle

////
TODO: add paragraph
////

[[interdapp_coammunications_protocol_sec]]
==== Inter-DApp communications protocol



[[whisper_sec]]
===== Whisper

////
TODO: add paragraph
////
https://github.com/ethereum/wiki/wiki/Whisper

https://github.com/ethereum/wiki/wiki/Whisper-Overview

////

TODO The following list of development tools overlaps with that in dev-tools.asciidoc. I suggest merging this list into that, and putting a cross-reference here instead.

////


[[dapp_frameworks_sec]]
=== DApp frameworks

There are many development frameworks and libraries written in various languages that make it easier to create and deploy a DApp.

[[truffle_sec]]
==== Truffle
Truffle is a popular Ethereum-focused DApp development environment. It provides an application management environment, testing framework and asset pipeline.

With Truffle, you get:

* Smart contract compilation, linking, deployment and binary management.
* Automated contract testing with Mocha and Chai.
* Configurable build pipeline with support for custom build processes.
* Scriptable deployment & migrations framework.
* Network management for deploying to many public & private networks.
* Interactive console for direct contract communication.
* Instant rebuilding of assets during development.
* External script runner that executes scripts within a Truffle environment.

Documentation: http://truffleframework.com/docs

GitHub: https://github.com/trufflesuite/truffle

Website: https://truffleframework.com

[[embark_sec]]
==== Embark
The Embark Framework focuses on serverless DApps. Embark integrates with all EVM-based blockchains (of which Ethereum is the most prominent, of course), decentralized storages services (including IPFS), and decentralized communication platforms (including Whisper and Orbit).

With Embark you can:

** Blockchain (EVM-based)
* Automatically deploy contracts and make them available in your JavaScript code. Embark watches for changes, and if you update a contract Embark will automatically redeploy the contracts (if needed) and the DApp.
* Access contracts from JavaScript, with Promises.
* Do test-driven development of contracts using JavaScript.
* Keep track of deployed contracts; deploy only when needed.
* Manage different chains (e.g testnet, private net, livenet).
* Easily manage complex systems of interdependent contracts.

** Decentralized storage (IPFS)
* Easily store & retrieve data in the DApp through EmbarkJS, including uploading and retrieving files.
* Deploy the full application to IPFS or Swarm.


** Decentralized Communication (Whisper, Orbit)
* Easily send and receive messages through P2P channels.

** Web Technologies
* Integrate with any web technology including React, Foundation, etc.
* Use any build pipeline or tool you wish, including grunt, gulp and webpack.

Getting started & documentation: https://embark.readthedocs.io

GitHub: https://github.com/embark-framework/embark

Website: https://github.com/embark-framework/embark

==== Emerald

Emerald Platform is a framework and set of tools to simplify the development of DApps and the integration of existing services with Ethereum-based blockchains.

Emerald provides:

* JavaScript library and React components to build a DApp
* SVG icons common for blockchain projects
* Rust library to manage private keys, including hardware wallets, and sign transactions
* Ready to use components and services that can be integrated into existing apps via the command line or JSON RPC API
* SputnikVM, a standalone EVM implementation that can be used for development and testing

It's platform agnostic and provides tools for various targets:

* Desktop app (using Electron)
* Mobile apps
* Web apps
* Command-line apps and scripting tools

Getting started & documentation: https://docs.etcdevteam.com

Github: https://github.com/etcdevteam/emerald-platform

Website: https://emeraldplatform.io



[[dapp_development_tool_sec]]
==== DApp (development tool)
DApp is a simple command line tool for smart contract development. It supports these common use cases:

* Easily use any version of `solc`
* Run unit tests and interactively debug contracts in a native EVM execution environment
* Create persistent testnets using Geth
* Easily deploy your dapp to any EVM blockchain

It was created in the spirit of the Unix design philosophy, which means it's a good citizen of the command line and can be easily composed with other tools. To get started, visit https://dapp.tools/dapp



////
TODO: add paragraph
////

[[live_dapps_sec]]
=== Live DApps

Here are some live DApps on the Ethereum network.

////
TODO: add paragraph
////

[[populous_sec]]
==== Populous
An Ethereum-based project aiming to disrupt the multi-million dollar invoice financing industry by creating a peer-to-peer blockchain based lending service.

Website: https://populous.co/

[[ethpm_sec]]
==== EthPM
A project aimed at bringing package management to the Ethereum ecosystem.

Website: https://www.ethpm.com/

[[radar_relay_sec]]
==== Radar Relay
DEX (Decentralized Exchange) focused on trading Ethereum tokens directly from wallet to wallet.

Website: https://radarrelay.com/

[[cryptokitties_sec]]
==== CryptoKitties
A game deployed on Ethereum that allows players to purchase, collect, breed and sell various types of virtual cats.
It represents one of the earliest attempts to deploy blockchain technology for recreational and leisurely purposes.

Website: https://www.cryptokitties.co

[[ethlance_sec]]
==== Ethlance
Ethlance is a platform for connecting freelancers and developers, both paying and receiving ether.

Website: https://ethlance.com/

[[decentraland_sec]]
==== Decentraland
Decentraland is a virtual reality platform powered by the Ethereum blockchain. Users can create, experience, and monetize content and applications.

Website: https://decentraland.org/

[[makerdao_sec]]
==== MakerDAO

One of Ethereum's oldest projects, MakerDAO offers the Dai stablecoin: an asset-backed hard currency for the 21st century. A stablecoin is a cryptocurrency that has low volatility against the world’s most important national currencies, thereby combining the advantages of a cryptocurrency and of a major fiat currency.

The MakerDAO system allows users to lock up their valuable Ethereum tokens as collateral and issue Dai against them. When they want to retrieve their assets later, they simply return the Dai they issued plus a fee based on how long it was outstanding. This simple principle means that each Dai is backed by some valuable asset held in the secure MakerDAO smart contract platform.

Dai has been operational since December 2017. For more details, see https://makerdao.com
