[[testnets]]
== Testnet Overview
=== What is a testnet?

A test network (testnet for short) is used to simulate the behavior of the main network. There are some publicly available test networks.
When any major change is about to be included in the main network, its tests are mostly done on these test networks.
These test networks are also used by a large number of developers for testing their applicactions before deploying them on the main network. 

=== Using Testnets

You can either connect to publicly available test networks or spawn a development network of your own.
First, let's use a public testnet for an easier setup. To use a public testnet requires some testnet ethers
and a connection to that network. For testnet ethers, we will discuss faucets. For the testnet connection,
we will discuss Metamask and Infura.

=== Getting Test Ether

Since testnets do not operate with real money, the incentive to secure the testnets by miners is low.
Therefore, the testnets must be differently protected against abuse and attacks.
As a result, faucets were created to distribute free test ether to developers in a controlled manner.

=== MetaMask and Testnets

MetaMask is a bridge that allows you to visit the distributed web of tomorrow in your browser today.
It allows you to run Ethereum DApps right in your browser without running a full Ethereum node.
MetaMask includes a secure identity vault, providing a user interface to manage your identities
on different sites and sign blockchain transactions. You can install the MetaMask add-on in
Chrome, Firefox, Opera, and the new Brave browser.

== Connecting to Testnets

=== Ethereum

==== Infura

Infura was born with the goal of delivering stable and reliable RPC access to the internal projects within ConsenSys.
As the Ethereum network began to grab the majority of blockchain developer mindshare, ConsenSys recognized
that Infura would be of broad interest to the entire ecosystem. It provides access to Ethereum APIs and IPFS gateways.

==== Ropsten

If you want to begin testing contracts on the Ropsten network, there are several faucets that you can
source your Ropsten ethers from. If a faucet does not work, try a different one.

* http://faucet.ropsten.be:3001/
This faucet provides the possibility to queue the address that should receive the test ether.

* MetaMask
MetaMask offers an option to buy ether.
If the Ropsten testnet is used, this buy option will allow selecting the Ropsten Test Faucet Service. You can access this faucet from this page.
It requires the Metamask extension to work. https://faucet.metamask.io/

* The bitfwd Ropsten Faucet
A ropsten faucet available at https://faucet.bitfwd.xyz/.

* Kyber Network Ropsten Faucet
Another ropsten faucet available at https://faucet.kyber.network/.

==== Rinkeby

The Rinkeby faucet is located at https://faucet.rinkeby.io/.
To request test ether it is necessary to make a public post on either Twitter, Goole Plus or Facebook.

==== Kovan

The Kovan testnet supports various methods to request test ether.
Further information can be found in the Kovan testnet GitHub Repository located at https://github.com/kovan-testnet/faucet/blob/master/README.md.

=== Ethereum Classic

==== Morden
Ethereum Classic currently runs a variant of the Morden testnet that is kept at feature parity with the Ethereum Classic live network. You can connect to it through either the gastracker RPC or by providing a flag to `geth` or `parity`

*Faucet:* http://testnet.epool.io/
*Gastracker RPC:* https://web3.gastracker.io/morden
*Block Explorer:* http://mordenexplorer.ethertrack.io/home
*Geth flag:* `geth --chain=morden`
*Parity flag:* `parity --chain=classic-testnet`

== History of Ethereum Testnets

https://www.ethnews.com/ropsten-to-kovan-to-rinkeby-ethereums-testnet-troubles

=== Proof-of-Work (Mining) vs. Proof-of-Authority (Federated Signing)

=== Morden

https://blog.ethereum.org/2016/11/20/from-morden-to-ropsten/

=== Ropsten

http://pool.ropsten.ethereum.org/

https://ropsten.etherscan.io/

=== Kovan

https://medium.com/@Digix/announcing-kovan-a-stable-ethereum-public-testnet-10ac7cb6c85f

https://kovan-testnet.github.io/website/

https://kovan.etherscan.io/

=== Rinkeby (Clique?)

https://www.rinkeby.io/

https://rinkeby.etherscan.io/
