== Ethereum Testnets

=== What is testnet?

=== Using Testnets

=== MetaMask and Testnets

=== Network Provider Infura

=== Getting test ether - Testnet Faucets

Since testnets do not operate with real money, the incentive to secure the testnets by miners is low.
Therefore, the testnets must be differently protected against abuse and attacks.
As a result, so-called faucets exist, which distribute free test ether to developers in a controlled manner.

==== Ropsten

If you want to begin testing contracts on the Ropsten network, there are several faucets that you can
source your Ropsten ethers from. If a faucet does not work, try a different one.

* http://faucet.ropsten.be:3001/
This faucet provides the possibility to queue the address that should receive the test ether.

* MetaMask
MetaMask offers an option to buy ether.
If the Ropsten testnet is used, this buy option will allow selecting the Ropsten Test Faucet Service. You can access this faucet from this page.
It requires the Metamask extension to work. https://faucet.metamask.io/

* The bitfwd Ropsten Faucet
A ropsten faucet available at https://faucet.bitfwd.xyz/.

* Kyber Network Ropsten Faucet
Another ropsten faucet available at https://faucet.kyber.network/.

==== Rinkeby

The Rinkeby faucet is located at https://faucet.rinkeby.io/.
To request test ether it is necessary to make a public post on either Twitter, Goole Plus or Facebook.

==== Kovan

The Kovan testnet supports various methods to request test ether.
Further information can be found in the Kovan testnet GitHub Repository located at https://github.com/kovan-testnet/faucet/blob/master/README.md.

=== History of Ethereum Testnets

https://www.ethnews.com/ropsten-to-kovan-to-rinkeby-ethereums-testnet-troubles

=== Proof-of-Work (Mining) vs. Proof-of-Authority (Federated Signing)

=== Morden

https://blog.ethereum.org/2016/11/20/from-morden-to-ropsten/

=== Ropsten

http://pool.ropsten.ethereum.org/

https://ropsten.etherscan.io/

=== Kovan

https://medium.com/@Digix/announcing-kovan-a-stable-ethereum-public-testnet-10ac7cb6c85f

https://kovan-testnet.github.io/website/

https://kovan.etherscan.io/

=== Rinkeby (Clique?)

https://www.rinkeby.io/

https://rinkeby.etherscan.io/
