== Ethereum Basics

=== What is a blockchain?
Traditionally, the IT industry has developed technologies that address a class of problems. For example, in the olden days (_when?_) a common problem was around efficient storage and retrieval of data. The IT industry responded with database technologies. (_some anecdotal references here_). In the same fashion, the blockchain technology aims at addressing the problem of *decentralized consensus*. To explore this problem of decentralized consensus, let us first define consensus.

==== Consensus
The English dictionary meaning of the word _consensus_ is "agreement over something between two or more parties". (__insert citation__). In business terms, _consensus_ could mean the agreement between two or more parties (internal to an organisation or external) on the value of parameter(s) of interest to all parties involved. For example, the parameter could be inventory levels, current location or status of a shipment, ownership of equipment and so on. Traditionally, the values of such parameters have been entrusted with a central organization. For example, the central bank of a country serves as the clearing house for all banking entities (__fix language__), the road transportation office is the organisation to decide automobile ownership and so on.

Therefore, the central organisation assumes the role of _custodian of truth_ and enforces that truth to all parties who repose their faith in such an organisation.

==== Decentralized Consensus
To understand the idea of decentralized consensus, let us ask the question as, _what if, there was no central custodian of truth and yet all parties agreed upon a truth_? This is a radical question and strikes at the very existence of a central authority. It is revolutionary also because of the expected change in societal behavior where, 'looking up' a central authority has been the way to arrive at certain facts, resolve disputes, etc.

Philosophy aside, the case of decentralized consensus is to arrive at the value of parameter(s) of interest without involving a central authority. For example, across the value chain of an industry, can the parties agree on a parameter of interest? How does a buyer of a high-end garment be sure of its provenance? Can a buyer be sure that an item of jewelery does not have 'conflict minerals'?

=== What is Bitcoin?
Bitcoin is the most visible implementation of blockchain technology. In terms of decentralized consensus, the parameter of interest is simply the balance in an account. Let us see the origin of this consensus problem.

In the good old days of non-electronic world, cash was the _de facto_ mechanism to conclude a transaction. So, a buyer would hand out $10 in his or her wallet to a seller in exchange of certain goods or services. At the end of the transaction, the balance in the buyer wallet is debited by $10 and the balance in the seller wallet is credited to by $10. Clean and simple - no further consensus is required on the balance in the wallets.

In the still good, but not so old days, Internet broke into scene and brought e-mail. With the 'carbon copy' (Cc) feature, it was no easy to type once and send the email to multiple recipients. If the email had an attachment of the image of a cute cat, then the image file would be replicated as many times as the recipients. Imagine money being transferred via e-mail. A $10 amount could then have been replicated and sent to multiple recipients! This glaring issue is the basis of *double spending* problem. In terms of consensus, the challenge would be the agreement on the account balance - the parameter of interest. And thus, core banking systems were born to play the role of custodian of truth on account balances. (__need evidences__)

Bitcoin establishes the decentralized consensus on account balance amongst all parties by eliminating the double spending problem without the need for a central authority.

=== What is Ethereum?
Ethereum is an open-source, globally decentralized computing infrastructure that executes programs called smart contracts. It uses a blockchain to synchronize and store the system state along with a cryptocurrency called ether to meter and constrain execution resource cost. __copied from here__ https://github.com/ethereumbook/ethereumbook/blob/develop/what-is.asciidoc#what-is-ethereum

==== Bitcoin state transition 
The Bitcoin implementation can be seen as an implementation of a state transaction system too, where, the state is the account balance. For example, at a certain point in time, there are only two account holders - A and B - each with a balance of $10. The account holder A, transfers $2 to B, in exchange for certain goods. Therefore, at a later point in time, the changed state is $8 balance with A and $12 balance with B. This change in state is not recorded in the systems of a central authority. Instead, it is in the Bitcoin ledger that exists on every computer in the Bitcoin network.

In summary, Bitcoin saves three things in the ledger: current balance in the account, transition and the to-be balance in the account. 

==== Generic state transition
What if, there was a decentralized system that maintained the transition of state of any system? For example, the movement of goods from a factory to a customer is a state transition of the produced goods. Ethereum is that decentralized system that allows for state transition without the need for a central authority.