[[testnets]]
== Testnet Overview
=== What is a testnet?

A test network (testnet for short) is used to simulate the behavior of the main Ethereum network. There are some publicly available test networks that are simply alternative Ethereum blockchains. The currency on these networks is worthless, but they are still useful since  functionality of contracts and protocol changes can be tested without disrupting the main Ethereum network or using real money. When any major change to the Ethereum protocol is about to be included in the main network, its tests are mostly done on these test networks. These test networks are also used by a large number of developers for testing applications before deploying them onto the main network. 

=== Using Testnets

You can either connect to publicly available test networks or spawn a development network of your own. First, let's use a public testnet for easier setup. To use a public testnet requires some testnet ethers and a connection to that network. For testnet ethers, faucets are used. To connect to testnets, we will discuss how to do so in various popular clients.

=== Getting Test Ether

Since testnets do not operate with real money, the incentive to secure the testnets by miners is low. Therefore, the testnets must protect themselves from abuse and attacks differently. As a result, faucets were created for these testnets to distribute free test ether to developers in a controlled manner (most faucets 'drip' ether at 1 ether every few seconds or so.) This controlled distribution of ether prevents users from abusing the chain since giving a limited supply of ether prevents them from writing too much to the chain or executing too many transactions. Additionally, some testnets have implemented Proof of Authentication schemes, where using a faucet requires authentication from a social media site with proper credentials.   

=== Connecting to Testnets

==== Metamask
Metamask fully supports the Ropsten, Kovan and Rinkeby testnets, but connecting to other testnets and local networks is also possible. In Metamask, simpy clicking the drop down that says 'Main Network' allows for switching networks. MetaMask offers an option to buy ether. If the Ropsten testnet is used, ether can be obtained from the Ropsten Test Faucet Service. You can access this faucet from this page. It requires the Metamask extension to work. https://faucet.metamask.io/

==== Infura

Infura was born with the goal of delivering stable and reliable RPC access to the internal projects within ConsenSys. As the Ethereum network began to grab the majority of blockchain developer mindshare, ConsenSys recognized that Infura would be of broad interest to the entire ecosystem. It provides access to Ethereum APIs and IPFS gateways. Using Infura with testnets is simple enough. Infura supports gatweays for the main net, Ropsten, Kovan, Rinkeby and INFURAnet (a custom testnet for Infura). Sending API calls to testnets from Infura simply involves changing the base URL for API calls.  More information on the details of these API calls is located at:
https://infura.io/docs/gettingStarted/chooseaNetwork  

==== Geth
//// TO DO: Loosely explain the geth commands to connect to a testnet

==== Parity
Connecting to a testnet in Parity requires using command-line arguments. For instance, to start Parity on the Ropsten testnet, run: 
----
parity --chain ropsten
----
Parity supports such commands for most testnets.


== Ethereum Testnets In Depth

==== Ropsten

If you want to begin testing contracts on the Ropsten network, there are several faucets that you can
source your Ropsten ethers from. If a faucet does not work, try a different one.

* http://faucet.ropsten.be:3001/
This faucet provides the possibility to queue the address that should receive the test ether.

* The bitfwd Ropsten Faucet
A ropsten faucet available at https://faucet.bitfwd.xyz/.

* Kyber Network Ropsten Faucet
Another ropsten faucet available at https://faucet.kyber.network/.

==== Rinkeby

The Rinkeby faucet is located at https://faucet.rinkeby.io/.
To request test ether it is necessary to make a public post on either Twitter, Goole Plus or Facebook.

==== Kovan

The Kovan testnet supports various methods to request test ether.
Further information can be found in the Kovan testnet GitHub Repository located at https://github.com/kovan-testnet/faucet/blob/master/README.md.

=== Ethereum Classic

==== Morden
Ethereum Classic currently runs a variant of the Morden testnet that is kept at feature parity with the Ethereum Classic live network. You can connect to it through either the gastracker RPC or by providing a flag to `geth` or `parity`

*Faucet:* http://testnet.epool.io/
*Gastracker RPC:* https://web3.gastracker.io/morden
*Block Explorer:* http://mordenexplorer.ethertrack.io/home
*Geth flag:* `geth --chain=morden`
*Parity flag:* `parity --chain=classic-testnet`

== History of Ethereum Testnets

https://www.ethnews.com/ropsten-to-kovan-to-rinkeby-ethereums-testnet-troubles

=== Proof-of-Work (Mining) vs. Proof-of-Authority (Federated Signing)

=== Morden

https://blog.ethereum.org/2016/11/20/from-morden-to-ropsten/

=== Ropsten

http://pool.ropsten.ethereum.org/

https://ropsten.etherscan.io/

=== Kovan

https://medium.com/@Digix/announcing-kovan-a-stable-ethereum-public-testnet-10ac7cb6c85f

https://kovan-testnet.github.io/website/

https://kovan.etherscan.io/

=== Rinkeby (Clique?)

https://www.rinkeby.io/

https://rinkeby.etherscan.io/


== Running Local Testnets
