== Gas

Because programs require computational "work" to perform an action or set of actions, there is a cost associated with calling on smart contracts and transacting on the Ethereum blockchain. This cost is related to the number of computational steps that the program undergoes. Unlike Bitcoin transaction fees which only takes into account the size of a transaction (kB), Ethereum smart contracts can perform an arbitrary number of computational steps. The higher the number of operations a program performs, the higher the cost to run it to completion. **Gas** is Ethereum's unit for measuring how much computational "work" an action or set of actions takes to perform. Every operation performed by a transaction or contract costs a certain number of gas.

To each operation, a fixed amount of gas is assigned some examples from the Ethereum yellow paper
- Adding two numbers costs 3 gas
- Calculating a Keccak256 hash costs 30 gas + 6 more gas for every 256 bits of data being hashed
- Sending a transaction costs 21000 gas

## Paying for gas

Gas cannot be "owned". It exists only inside the Ethereum Virtual Machine (EVM) as a count of how much computational work is being performed. The sender is charged a transaction fee in Ether, which is then converted to gas and then back to Ether as block rewards for the miners. These conversion steps are in place to separate the price for the computation (tied to amount of "work") from the price of Ether (tied to market fluctuations).

## Gas cost vs. gas price

While the **gas cost** is a measure of operational steps performed in the EVM, the gas itself also has a **gas price** measured in Ether. When performing a transaction, the sender specifies the gas price they are willing to pay (in Ether) for each unit of gas, allowing the market to decide the relationship between the price of ether and the cost of computing operations (as measured in gas).

** Total gas used x Gas price paid = Total transaction fee **

## Gas limit and running out of gas

Before sending a transaction, senders must specify a **gas limit** - the maximum amount of gas they are willing to buy. If the gas used goes over this limit, i.e. if the transaction "runs of out gas" during execution, the operation is terminated but the sender will not get their funds back, as the miners have already performed the work up to that point and will be compensated for doing so.

== Questions that need to be answered in this section

* x What is Gas
* x What is gas cost
* x What is the gas limit
* x How is gas counted
* x Who pays gas
* x What happens if there's not enough gas
* x Is gas paid if there's not enough?
* Who pays for contract calls if intiated by EOA
* Who pays if the contract initiates the message?
* How are contracts funded
* Can you set the gas limit above the balance you have?
* When is gas actually charged
* Can you double spend gas? Why not?
* how are transactions sequenced when sent concurrently (same block), in terms of gas and balance?
* How can a contract run out of gas?

== Outline of gas section
