[preface]
== Quick Glossary

This quick glossary contains many of the terms used in relation to Ethereum. These terms are used throughout the book, so bookmark this for a quick reference.

////

Please add terms here, by doing a pull request!

If you can't write a definition, then do a pull request to add only the words you think should be defined and leave the definition empty for someone else to add later.


////


address::
    Most generally this is the place where you receive transactions on the blockchain. More specifically it is the right most 160-bits of a Keccak hash of a ECDSA public key.

BIP::
    Bitcoin Improvement Proposals.  A set of proposals that members of the bitcoin community have submitted to improve bitcoin. For example, BIP-21 is a proposal to improve the bitcoin uniform resource identifier (URI) scheme.

blockchain::
	A list of validated blocks, each linking to its predecessor all the way to the genesis block.


consensus::
    When several nodes, usually most nodes on the network, all have the same blocks in their locally-validated best block chain.
    Not to be confused with consensus rules.

consensus rules::
    The block validation rules that full nodes follow to stay in consensus with other nodes. Not to be confused with consensus.


ECDSA::
    Elliptic Curve Digital Signature Algorithm or ECDSA is a cryptographic algorithm used by Ethereum to ensure that funds can only be spent by their rightful owners.

EIP::
    Ethereum Improvement Proposals.


EVM::
    Ethereum Virtual Machine.


gas::
    A virtual currency used in Ethereum to constrain computation of smart contracts. The Ethereum Virtual Machine uses an accounting mechanism to measure the consumption of gas and constrain (limit) the consumption of computing resources. See Turing-Complete.


genesis block::
	The first block in the blockchain, used to initialize the cryptocurrency.

hash::
    A digital fingerprint of some binary input.



HD wallet::
    Wallets using the Hierarchical Deterministic (HD Protocol) key creation and transfer protocol (BIP32).

HD wallet seed::
    HD wallet seed or root seed is a potentially-short value used as a seed to generate the master private key and master chain code for an HD wallet.


miner::
    A network node that finds valid proof of work for new blocks, by repeated hashing.

network::
    A peer-to-peer network that propagates transactions and blocks to every Ethereum node (network participant).

node::
    A computer that is participating in the peer-to-peer network.

Proof-of-Stake::
    Proof-of-Stake (PoS) is a method by which a cryptocurrency blockchain network aims to achieve distributed consensus. Proof-of-Stake asks users to prove ownership of a certain amount of currency (their "stake" in the currency)

Proof-of-Work::
    A piece of data (the proof) that requires significant computation to find. In Ethereum, miners must find a numeric solution to the Ethash algorithm that meets a network-wide target, the difficulty target.

reward::
    An amount included in each new block as a reward by the network to the miner who found the Proof-of-Work solution.

Satoshi Nakamoto::
    Satoshi Nakamoto is the name used by the person or people who designed Bitcoin and created its original reference implementation, Bitcoin Core. As a part of the implementation, they also devised the first blockchain database. In the process they were the first to solve the double spending problem for digital currency. Their real identity remains unknown.

secret key (aka private key)::
	The secret number that allows Ethereum users to prove ownership of an account or contracts, by producing a digital signature (see public key, address, ECDSA).

SHA::
    The Secure Hash Algorithm or SHA is a family of cryptographic hash functions published by the National Institute of Standards and Technology (NIST).


transaction::

wallet::
    Software that holds all your secret keys. Used as the interface to access and control your Ethereum accounts and contracts.
