[preface]
== Quick Glossary

This quick glossary contains many of the terms used in relation to Ethereum. These terms are used throughout the book, so bookmark this for a quick reference.

////

Please add terms here, by doing a pull request!

If you can't write a definition, then do a pull request to add only the words you think should be defined and leave the definition empty for someone else to add later.

Comment from Gitter:
    Andreas M. Antonopoulos @aantonop mar. 26 19:42 (2018)
    Capitalize ALL THE WORDS

////

Account::
    An object containing an address, balance and nonce, and optional storage and code. An account can be a contract account or an EOA (externally owned account).

Address::
    Most generally, this represents an EOA or contract, which can receive (destination address) or send (source address) transactions on the blockchain. More specifically, it is the right most 160-bits of a Keccak hash of an ECDSA public key.

Assert::
    In Solidity assert(false) compiles to *0xfe*, which is an invalid opcode, using up all remaining gas, and reverting all changes.
    When an assert() statement fails, something very wrong and unexpected should be happening, and you will need to fix your code.
    You should use assert to avoid conditions which should never, ever be possible.

Big-endian::
    A positional number representation where the most significant digit is first. The opposite of little-endian where the least significant digit is first.

BIP::
    Bitcoin Improvement Proposals.  A set of proposals that members of the Bitcoin community have submitted to improve Bitcoin. For example, BIP-21 is a proposal to improve the Bitcoin uniform resource identifier (URI) scheme.

Block::
    A block is added to the Ethereum network by miners and is a collection of required information (a block header) about the comprised transactions, and a set of other block headers known as ommers.

Blockchain::
	A sequence of blocks validated by the proof-of-work system, each linking to its predecessor all the way to the genesis block. This varies from the Bitcoin protocol's in that it does not have a block size limit, it instead uses varying gas limits.

Byzantium::
  Byzantium is the first of two hard forks for Metropolis development stage. It included EIP-649: Metropolis Difficulty Bomb Delay and Block Reward Reduction, where the Ice Age (see below) was delayed by 1 year, and the block reward was reduced from 5 to 3 ether.

Compiling::
	Converting code written in a high-level programming language (e.g. Solidity) into a lower level language (e.g. EVM bytecode).

Consensus::
    When several nodes, usually most nodes on the network, all have the same blocks in their locally-validated best block chain.
    Not to be confused with consensus rules.

Consensus rules::
    The block validation rules that full nodes follow to stay in consensus with other nodes. Not to be confused with consensus.

Constantinople::
  The second part of the Metropolis stage, planned for mid-2018. Expected to include a switch to hybrid Proof-of-Work/Proof-of-Stake consensus algorithm, among other changes.

Contract account::
    An account containing code that executes whenever it receives a transaction from another account (EOA or contract).

Contract creation transaction::
	A special transaction, with the "zero address" as the recipient, that is used to register a contract and record it on the Ethereum blockchain (see "zero address").

DApp::
    Decentralised Application. At the very least, it is a smart contract and a web user-interface. More broadly, a DApp is a web application that is built on top of open, decentralized, peer-to-peer infrastructure services. In addition, many DApps include decentralized storage and/or message protocol and platform.

DAO::
  Decentralised Autonomous Organization. Companies and other organizations which operate without hierarchical management. Also may refer to a contract named "The DAO" launched on 30th April 2016, which was then hacked in June 2016 and ultimately motivated a hard fork (codenamed DAO) at block #1,192,000 that reversed the hacked DAO contract and caused Ethereum and Ethereum Classic to split into two competing systems.

Deed::
  Non-fungible token standard introduced in ERC721 proposal. Unlike ERC20 tokens, deeds prove ownership and are not interchangeable, though they are not recognized as "legal documents" in any jurisdiction, at least not currently.

Difficulty::
  A network-wide setting that controls how much computation is required to produce a proof of work.

Digital signature::
  A digital signing algorithm is a process by which a user can produce a short string of data called a "signature" of a document using a private key such that anyone with the corresponding public key, the signature and the document can verify that (1) the document was "signed" by the owner of that particular private key, and (2) the document was not changed after it was signed.

ECDSA::
    Elliptic Curve Digital Signature Algorithm or ECDSA is a cryptographic algorithm used by Ethereum to ensure that funds can only be spent by their rightful owners.

EIP::
    Ethereum Improvement Proposals are standards for the Ethereum platform. An EIP is a design document providing information to the Ethereum community, describing a new feature or its processes or environment. For more information, see https://github.com/ethereum/EIPs (also see the definition for ERC, below).

Entropy::
    In the context of Cryptography, lack of predictability or level of randomness. When generating secret information, such as master private keys, algorithms usually rely on a source of high entropy to ensure the output is unpredictable.

ENS::
  Ethereum Name Service. For more information, see https://github.com/ethereum/ens/

EOA::
    Externally Owned Account. These are accounts created by or for human users of the Ethereum network.

ERC::
    Ethereum Request for Comments. Some EIPs are labeled as ERCs, which denotes proposals attempting to define a specific standard of Ethereum usage.

// Should we use version numbers or release names?
Ethash::
    A Proof-of-Work algorithm for Ethereum 1.0. For more information, see https://github.com/ethereum/wiki/wiki/Ethash

Ether::
    Ether is the native cryptocurrency used by the Ethereum ecosystem that covers gas costs when executing Smart Contracts. Its symbol is Ξ, the Greek uppercase Xi character.

Event::
    An event allows the use of EVM logging facilities, which in turn can be used to “call” JavaScript callbacks in the user interface of a DApp, which listen for these events. For more information, see http://solidity.readthedocs.io/en/develop/contracts.html#events

EVM::
    Ethereum Virtual Machine. The EVM is a simple stack-based architecture. In Ethereum, the execution model specifies how the system state is altered given a series of bytecode instructions and a small tuple of environmental data.
    This is specified through a formal model of a virtual state machine, known as the Ethereum Virtual Machine (EVM).

EVM Assembly Language::
    A human-readable form of EVM-code.

Fallback function::
    It's like a fishing net to catch all the ether that is sent to a contract.
    
Faucet::
  A website that dispenses rewards in the form of free test ether for developers who want to do test on testnets.

Frontier::
  The initial test development stage of Ethereum, lasted from July 30th 2015 to March 2016.

Ganache::
  A personal blockchain for Ethereum development. One can use Ganache to deploy contracts, develop applications, and run tests. It is available as a desktop application for Windows, Mac, and Linux.

// The word currency here might 'clash' with Ether.
//

TODO: Change for Clarity

//
Gas::
    A virtual fuel used in Ethereum to execute smart contracts. The Ethereum Virtual Machine uses an accounting mechanism to measure the consumption of gas and constrain (limit) the consumption of computing resources. See Turing-Complete.
    Gas is a unit of computation that is incurred per instruction of Smart Contract executed. The gas is pegged at Ether cryptocurrency. The gas is analogous to talk time on a cellular network. Thus, the price of running a transaction in fiat currency is `gas * (ETH/gas) * (fiat currency/ETH)`.

Gas limit::
  When talking about blocks, they too, have a field called gas limit. It defines the maximum amount of gas all transactions in the whole block combined are allowed to consume.

Genesis block::
	The first block in the blockchain, used to initialize a particular network and its cryptocurrency.

Geth::
  Go Ethereum. One of the most prominent implementations of the Ethereum protocol written in Go.

Hard fork::
  Hard fork, also known as Hard-Forking Change, is a permanent divergence in the blockchain, commonly occurs when non-upgraded nodes can't validate blocks created by upgraded nodes that follow newer consensus rules. Not to be confused with fork, soft fork, software fork or Git fork.

Hash::
   A fixed-length fingerprint of variable-size input produced by a hash function.

HD wallet::
    Wallets using the Hierarchical Deterministic (HD Protocol) key creation and transfer protocol (BIP32).

////

TODO change for clarity

////
HD wallet seed::
    HD wallet seed or root seed is a potentially-short value used as a seed to generate the master private key and master chain code for an HD wallet. The wallet seed can be represented by mnemonic words making it easier for humans to copy, backup and restore private keys.

Homestead::
  The second development stage of Ethereum, launched in March 2016 at block #1,150,000.

Ice Age::
  A hard fork of Ethereum at block #200,000 to introduce an exponential difficulty increase (aka Difficulty Bomb), motivating a transition to Proof-of-Stake.

// In case of Ethereum, perhaps, includes a blockchain explorer too?
IDE (Integrated Development Environment)::
	An integrated user interface that combines a code editor, compiler, runtime, and a debugger.

Immutable Deployed Code Problem::
  Once a contract's (or library's) code is deployed it becomes immutable. Being able to fix possible bugs and add new features is key for the software development cycle. This represents a challenge for smart contract development.

Inter exchange Client Address Protocol (ICAP)::
  An Ethereum Address encoding that is partly compatible with the International Bank Account Number (IBAN) encoding, offering a versatile, checksummed and interoperable encoding for Ethereum Addresses. ICAP addresses can encode Ethereum Addresses or common names registered with an Ethereum name registry. They always begin with XE. The aim is to introduce a new IBAN country code: XE, Ethereum E prefixed with the "extended" X, as used in non-jurisdictional currencies (e.g. XBT, XRP, XCP).

Internal transaction (also "message")::
    A transaction sent from a contract account to another contract account or an EOA.

Keccak256::
  Cryptographic hash function used in Ethereum. Keccak256 was standardised to SHA-3.

Key Derivation Function (KDF)::
  Also known as a password stretching algorithm, it is used by keystore format which to protect against brute-force, dictionary, or rainbow table attacks against the passphrase encryption. It repeatedly hashes the passphrase.

Keystore File::
  A JSON-encoded file that contains a single (randomly generated) private key, encrypted by a passphrase for extra security.

LevelDB::
  LevelDB is an open source on-disk key-value store. LevelDB is a light-weight, single-purpose library for persistence with bindings to many platforms.

Library::
  A library in Ethereum is a special type of contract that has no payable functions, no fallback function, and no data storage. Therefore, it cannot receive or hold ether, or store data. A library serves as previously deployed code that other contracts can call for read-only computation.
  
Lightweight client::
  A lightweight client is an Ethereum client that does not store a local copy of the blockchain, or validate blocks and transactions. It offers the functions of a wallet and can create and broadcast transactions.

////

TODO: Provide a crisp definition

////

Merkle Patricia Tree::

Message::
    An internal transaction that is never serialized and only sent within the EVM.

Metropolis::
  Metropolis is the third development stage of Ethereum, launched in October 2017.

METoken::
  Mastering Ethereum Token. An ERC20 token used for demonstration in this book.

Miner::
    A network node that finds valid proof of work for new blocks, by repeated hashing.

Mist::
  Mist is the first ever Ethereum enabled browser, built by the Ethereum Foundation. It also contains a browser based wallet that was the first ever implementation of the ERC20 token standard (Fabian Vogelsteller, author of ERC20 was also the main developer in Mist). Mist was also the first wallet to introduce the camelCase checksum (EIP-155, see <<eip-155>>). Mist runs a full node, and offers a full DApp browser with support for Swarm based storage and ENS addresses.

Network::
    A peer-to-peer network that propagates transactions and blocks to every Ethereum node (network participant).

Node::
    A software client that is participating in the peer-to-peer network.

Nonce::
    In cryptography, the term nonce is used to refer to a value that can only be used once. There are two types of nonce used in Ethereum.

     - Account nonce - It's simply the transaction count of an account.
     - Proof of work nonce - The random value in a block that was used to get the proof of work satisfied (depending on the difficulty at the time).

Ommer::
    A child block of an ancestor that is not itself an ancestor. When a miner finds a valid block, another miner may have published a competing block which is added to the tip of the blockchain. Unlike bitcoin, orphaned blocks in Ethereum can be included by newer blocks as ommers and receive a partial block reward. The term "ommer" is the preferred gender neutral term for the sibling of a parent node, but is also referred to as an "uncle".

Paralysis Problem::
  A common powerful approach to key management for cryptocurrencies is multisig transactions, referred to more generally as secret sharing.
  But, what would happen if one of the shared keys was lost? The result would be a complete loss of all of the funds. +
  This isn’t the only bad scenario. It’s also possible that the key-share holders have different ideas about how the money should be spent, and can’t come to an agreement. +
  We use the term _Paralysis Problem_ to denote any of these awkward situations.

Paralysis Proof System::
  Paralysis Proofs help address a pervasive key-management problem in cryptocurrencies. See *Paralysis Problem*. +
  A Paralysis Proof System can tolerate system paralysis in settings where players fail to act in concert. +
  A Paralysis Proof System can be realized relatively easily for Ethereum using a smart contract.

Parity::
  One of the most prominent interoperable implementations of the Ethereum client software.

Proof-of-Stake::
    Proof-of-Stake (PoS) is a method by which a cryptocurrency blockchain protocol aims to achieve distributed consensus. Proof-of-Stake asks users to prove ownership of a certain amount of cryptocurrency (their "stake" in the network) in order to be able to participate to the validation of transactions.

Proof-of-Work::
    A piece of data (the proof) that requires significant computation to find. In Ethereum, miners must find a numeric solution to the Ethash algorithm that meets a network-wide difficulty target.

Receipt::
    Data returned by an Ethereum client to represent the result of a particular transaction, including a hash of the transaction, its block number, the amount of gas used and, in case of deployment of a Smart Contract, the address of the Contract.

Reentrancy Attack::
  This attack can be reproduced when the Attacker contract calls to a Victim contract function, let's call it victim.withdraw(), in manner that before the original call to that contract function ever finishes, it calls the victim.withdraw() method again which continues to recursively call itself.
  This recursive call can be implemented from a fallback function of the Attacker contract.
  The only trick that the attacker has to perform is to break that recursive call before running out of gas and so avoiding the stolen ether be reverted.

[require-sentence]
Require::
    In Solidity, require(false) compiles to *0xfd* which is the *REVERT* opcode. The REVERT instruction provides a way to stop execution and revert state changes, without consuming all provided gas and with the ability to return a reason. +
    The require function should be used to ensure valid conditions, such as inputs, or contract state variables are met, or to validate return values from calls to external contracts. +
    Prior to the *Byzantium* network upgrade there were two practical ways to revert a transaction: running out of gas or executing an invalid instruction. Both of these options consumed all remaining gas. +
    When you look up this opcode in the *Yellow Paper* prior to the *Byzantium* network upgrade, you can't find it and because there was no specification for that opcode, when the EVM reached it, it thrown an _invalid opcode error_. +

Revert::
    Use revert() when you need to handle the same type of situations as <<require-sentence, require()>> but with more complex logic.
    For instances, if your code have some nested if/else logic flow, you will find that it makes sense to use <<require-sentence, require()>> instead of require().

Reward::
    An amount, in Ether (ETH), included in each new block as a reward by the network to the miner who found the Proof-of-Work solution.

Recursive Length Prefix (RLP)::
    RLP is an encoding standard, designed by the Ethereum developers to encode and serialize objects (data structures) of arbitrary complexity and length.

Satoshi Nakamoto::
    Satoshi Nakamoto is the name used by the person or people who designed Bitcoin and created its original reference implementation, Bitcoin Core. As a part of the implementation, they also devised the first blockchain database. In the process they were the first to solve the double spending problem for digital currency. Their real identity remains unknown.

Vitalik Buterin::
    Vitalik Buterin is a Russian-Canadian programmer and writer primarily known as the co-founder of Ethereum and as the co-founder of Bitcoin Magazine.

Gavin Wood::
    Gavin Wood is a British programmer who is the co-founder and former CTO of Ethereum. In August 2014 he proposed Solidity, a contract-oriented programming language for writing smart contracts.

Secret key (aka private key)::
    The secret number that allows Ethereum users to prove ownership of an account or contracts, by producing a digital signature (see public key, address, ECDSA).

SHA::
    The Secure Hash Algorithm or SHA is a family of cryptographic hash functions published by the National Institute of Standards and Technology (NIST).

SELFDESTRUCT opcode::
  Smart contracts will exist and be executable as long as the whole network exists. They will disappear from the blockchain if they were programmed to self destruct or performing that operation using delegatecall or callcode.
  Once self-destruct operation is performed, the remaining Ether stored at the contract address is sent to another address and the storage and code is removed from the state.
  Although this is the expected behavior, the pruning of self-destructed contracts may or may not be implemented by Ethereum clients.
  SELFDESTRUCT was previously called SUICIDE, with EIP6, SUICIDE was renamed to SELFDESTRUCT.

Serenity::
  The fourth and final development stage of Ethereum. Serenity does not yet have a planned release date.

Serpent::
	A procedural (imperative) programming language with syntax similar to Python. Can also be used to write functional (declarative) code, though it is not entirely free of side-effects. Used sparsely. First created by Vitalik Buterin.

////
TODO: Can be improved
////

Smart Contract::
  A program which executes on the Ethereum's computing infrastructure.

Solidity::
	A procedural (imperative) programming language with syntax that is similar to JavaScript, C++ or Java. The most popular and most frequently used language for Ethereum smart contracts. First created by Gavin Wood (co-author of this book).

Solidity inline assembly::
   Inline assembly is contained code within solidity that use EVM Assembly, which can be seen as the human-readable form of EVM-code. Inline assembly tries to facilitate inherent difficulty and other issues arising when writing manual assembly.

Spurious Dragon::
  A hard fork at block #2,675,00 to address more denial of service attack vectors, and another state clearing. Also, a replay attack protection mechanism.

Swarm::
  A decentralised (P2P) storage network. It is used along with Web3 and Whisper to build DApps.

Tangerine Whistle::
  A hard fork at block #2,463,00 to change the gas calculation for certain IO-heavy operations and to clear the accumulated state from a denial of service attack, which exploited the low gas cost of those operations.
  
Testnet::
  A test network (testnet for short) is used to simulate the behavior of the main Ethereum network.

Transaction::
  Data committed to the Ethereum Blockchain signed by an originating account, targeting a specific address. The transaction contains metadata such as the gas limit for the transaction.

Truffle::
  The most popular Ethereum Development Framework. It is composed of several NodeJS packages and can be installed using Node Package Manager (NPM).

////

TODO: Provide a crisp definition

////
Turing Complete::

Vyper::
  A high-level programming language, similar to Serpent with Python-like syntax. Intended to get closer to a pure-functional language. First created by Vitalik Buterin.

Wallet::
    Software that holds all your secret keys. Used as the interface to access and control your Ethereum accounts and interact with Smart Contracts. Notice that keys need not be stored in your wallet and can be retrieved from an offline storage (e.g. USB flash drive or paper) for improved security. Despite the name, wallets never store the actual coins or tokens.

Web3::
  The third version of the web. First proposed by Gavin Wood, Web3 represents a new vision and focus for web applications: from centrally owned and managed applications, to applications built on decentralized protocols.

Wei::
  The smallest denomination of ether. 10^18^ Wei = 1 ether.

Whisper::
  A decentralised (P2P) messaging service. It is used along with Web3 and Swarm to build DApps.

Zero address::
  A special Ethereum address, with all 20-bytes as zeros, that is specified as a destination address in the "contract creation transaction".
