

== Introduction to Ethereum

=== History

=== Currency units

Ethereum's currency unit is called _ether_ and is subdivided into smaller units, down to the smallest unit possible which is named _wei_. One _ether_ is 1 quintilion _wei_ (1 x 10^18^ or 1,000,000,000,000,000,000). You may hear people refer to the currency "Ethereum" too but this is a common beginner mistake.

The value of ether is always represented internally in Ethereum as integer multiples of _wei_. When you transact 1 ether, the transaction encodes 10^18^ wei as the value.

Ether's various denominations have a both a _scientific name_ using the International System of units (_SI_), and a colloquial name that pays homage to many of the great minds of cryptography and computer science.

Table <<ether_units>> shows the various units, their colloquial (common) name and their SI name. In keeping with the internal representation of value, the table shows all denominations in wei (first row), with ether shown as 10^18^ wei in the 7th row:

[[ether_units]]
.Ether Denominations and Unit Names
[options="header"]
|===
| Value (in wei) | Exponent | Common Name | SI Name
| 1 | 1 | wei | wei
| 1,000 | 10^3^ | babbage | kilowei or femtoether
| 1,000,000 | 10^6^ | lovelace | megawei or picoether
| 1,000,000,000 | 10^9^ | shannon | gigawei or nanoether
| 1,000,000,000,000 | 10^12^ | szabo | microether or micro
| 1,000,000,000,000,000 | 10^15^ | finney | milliether or milli
| _1,000,000,000,000,000,000_ | _10^18^_ | _ether_ | _ether_
| 1,000,000,000,000,000,000,000 | 10^21^ | grand | kiloether
| 1,000,000,000,000,000,000,000,000 | 10^24^ | | megaether
|===

=== Types of accounts: EOA and contracts

==== Sending Ether from an EOA to an EOA

=== Ethereum Transaction Basics:

Compare to bitcoin: single input, single output.

Source /Destination
.......... EOA .........  contract

EOA ........ X ..........   Y

Contract..... Z   ...........  Q

Four types?

One type, four combinations

Source, dest, signature, amount, gas limit, gas price, nonce, data

Tx is simpler than bitcoin, complexity is at a higher level (EVM)

==== Gas: quick intro


==== A simple contract

==== Registering (?) the contracts

==== Using the contracts
