[preface]
[[preface]]
== Preface

This book is a collaboration between Andreas M. Antonopoulos and Gavin Wood. A series of fortunate coincidences brought these two authors together in an effort that galvanized hundreds of contributors to produce this book, in the best spirit of open source and the creative commons culture.

Gavin had been wishing to write a book that expanded on the Yellow Paper (his technical description of the Ethereum protocol) for some time, primarily to open it up to a wider audience than the original Greek-letter-infused document could possibly allow.

Plans were underway&#x2014;a publisher had been found&#x2014;when Gavin got talking to Andreas, whom he had known from the very beginning of his tenure with Ethereum as a notable personality in the space.

Andreas had recently published the first edition of his book _Mastering Bitcoin_ (O'Reilly), which quickly became the authoritative technical guide to Bitcoin and cryptocurrencies. Almost as soon as the book was published, his readers started asking him, "When will you write 'Mastering Ethereum'?" Andreas was already considering his next project and found Ethereum to be a compelling technical subject.

Finally, in May 2016, Gavin and Andreas were both coincidentally in the same city at the same time. They met up for a coffee to chat about working on the book together. With both Andreas and Gavin being devotees of the open source paradigm, they both committed to making this a collaborative effort, released under a Creative Commons license. Thankfully, the publisher, O'Reilly Media, was happy to agree, and the _Mastering Ethereum_ project was officially launched.


=== How to Use This Book

The book is intended to serve both as a reference manual and as a cover-to-cover exploration of Ethereum. The first two chapters offer a gentle introduction, suitable for novice users, and the examples in those chapters can be completed by anyone with a bit of technical skill. Those two chapters will give you a good grasp of the basics and allow you to use the fundamental tools of Ethereum. <<ethereum_clients_chapter>> and beyond are intended mainly for programmers and include many technical topics and programming examples. 

To serve as both a reference manual and a cover-to-cover narrative about Ethereum, the book inevitably contains some duplication. Some topics, such as _gas_, have to be introduced early enough for the rest of the topics to make sense, but are also examined in depth in their own sections.  

Finally, the book's index allows readers to find very specific topics and the relevant sections with ease, by keyword. 

[[intended_audience_sec]]
=== Intended Audience

((("intended audience")))This book is mostly intended for coders. If you can use a programming language, this book will teach you how smart contract blockchains work, how to use them, and how to develop smart contracts and decentralized applications with them. The first few chapters are also suitable as an in-depth introduction to Ethereum for noncoders.



[[conventinons_used_sec]]
=== Conventions Used in This Book

((("typographical conventions")))The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or values determined by context.


[TIP]
====
This icon signifies a tip or suggestion.
====

[NOTE]
====
This icon signifies a general note.
====

[WARNING]
====
This icon indicates a warning or caution.
====

[[code_examples_sec]]
=== Code Examples

((("code examples, obtaining and using")))The examples are illustrated in Solidity, Vyper, and JavaScript, and using the command line of a Unix-like operating system. All code snippets are available in the GitHub repository under the _code_ subdirectory. Fork the book code, try the code examples, or submit corrections via GitHub: https://github.com/ethereumbook/ethereumbook.

All the code snippets can be replicated on most operating systems with a minimal installation of compilers, interpreters, and libraries for the corresponding languages. Where necessary, we provide basic installation instructions and step-by-step examples of the output of those instructions.

Some of the code snippets and code output have been reformatted for print. In all such cases, the lines have been split by a backslash (+\+) character, followed by a newline character. When transcribing the examples, remove those two characters and join the lines again and you should see identical results to those shown in the example.

All the code snippets use real values and calculations where possible, so that you can build from example to example and see the same results in any code you write to calculate the same values. For example, the private keys and corresponding public keys and addresses are all real. The sample transactions, contracts, blocks, and blockchain references have all been introduced to the actual Ethereum blockchain and are part of the public ledger, so you can review them.

[[using_code_examples_sec]]
=== Using Code Examples

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you're reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O'Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product's documentation does require permission.

((("attribution")))We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, ISBN, and copyright. For example: &#x201c;_Mastering Ethereum_ by Andreas M. Antonopoulos and Gavin Wood (O'Reilly). Copyright 2019 The Ethereum Book LLC and Gavin Wood, 978-1-491-97194-9."

((("open source licenses")))Some editions of this book are offered under an open source license, such as https://creativecommons.org/licenses/by-nc/4.0/[CC-BY-NC], in which case the terms of that license apply.

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== References to Companies and Products

All references to companies and products are intended for educational, demonstration, and reference purposes. The authors do not endorse any of the companies or products mentioned. We have not tested the operation or security of any of the products, projects or code segments shown in this book. Use them at your own risk!

[[ethereum_sddresses_and_transactions_sec]]
=== Ethereum Addresses and Transactions in this Book

((("getting started", "warnings and cautions")))((("warnings and cautions", "avoid sending money to addresses appearing in book")))((("keys and addresses", "warnings and cautions")))((("transactions", "warnings and cautions")))((("blockchain applications", "warnings and cautions")))((("QR codes", "warnings and cautions")))The Ethereum addresses, transactions, keys, QR codes, and blockchain data used in this book are, for the most part, real. That means you can browse the blockchain, look at the transactions offered as examples, retrieve them with your own scripts or programs, etc.

However, note that the private keys used to construct the addresses printed in this book have been "burned." This means that if you send money to any of these addresses, the money will either be lost forever or (more likely) appropriated, since anyone who reads the book can take it using the private keys printed herein.

[WARNING]
====
DO NOT SEND MONEY TO ANY OF THE ADDRESSES IN THIS BOOK. Your money will be taken by another reader, or lost forever.
====

[[oreilly_safari_sec]]
=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
pass:[<a href="https://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (formerly Safari Books Online) is a membership-based training and reference platform for enterprise, government, educators, and individuals.
====

Members have access to thousands of books, training videos, Learning Paths, interactive tutorials, and curated playlists from over 250 publishers, including O'Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, and Course Technology, among others.

For more information, please visit pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em>http://oreilly.com/safari</em></a>].

[[how_to_contact_us_sec]]
=== How to Contact Us

Information about _Mastering Ethereum_ as well as the Open Edition and translations are available at
link:$$https://ethereumbook.info/$$[].

((("comments and questions")))((("contact information")))Please address comments and questions concerning this book to the publisher:

++++
<ul class="simplelist">
  <li>O'Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (in the United States or Canada)</li>
  <li>707-829-0515 (international or local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

Send comments or technical questions about this book to pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

For more information about our books, courses, conferences, and news, see our website at link:$$https://www.oreilly.com$$[].

Find us on Facebook: link:$$https://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$https://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$https://www.youtube.com/oreillymedia$$[]




==== Contacting Andreas

You can contact Andreas M. Antonopoulos on his personal site:
link:$$https://antonopoulos.com/$$[]

Subscribe to Andreas's channel on YouTube:
link:$$https://www.youtube.com/aantonop$$[]

Like Andreas's page on Facebook:
link:$$https://www.facebook.com/AndreasMAntonopoulos$$[]

Follow Andreas on Twitter:
link:$$https://twitter.com/aantonop$$[]

Connect with Andreas on LinkedIn:
link:$$https://linkedin.com/company/aantonop$$[]

Andreas would also like to thank all of the patrons who support his work through monthly donations. You can support Andreas on Patreon at
link:$$https://patreon.com/aantonop$$[].


==== Contacting Gavin

You can contact Dr. Gavin Wood on his personal site:
link:$$http://gavwood.com/$$[]

Follow Gavin on Twitter:
link:$$https://twitter.com/gavofyork$$[]

Gavin generally hangs out in the Polkadot Watercooler on Riot.im:
link:$$http://bit.ly/2xciG68$$[]


[[acknowledgments_sec]]
=== Acknowledgments by Andreas

I owe my love of words and books to my mother, Theresa, who raised me in a house with books lining every wall. My mother also bought me my first computer in 1982, despite being a self-described technophobe. My father, Menelaos, a civil engineer who published his first book at 80 years old, was the one who taught me logical and analytical thinking and a love of science and engineering.

Thank you all for supporting me throughout this journey.

=== Acknowledgments by Gavin

My mother secured my first computer for me from a neighbor when I was 9 years old, without which my technical progress would no doubt have been lessened. I also owe her my childhood fear of electricity and must acknowledge Trevor and my grandparents, who performed the grave duty of "watching me plug it in" time after time, and without whom said computer would have been useless. I must also acknowledge the various educators I have been lucky to have through my life, from said neighbor Sean (who taught me my first computer program), to Mr. Quinn my primary school teacher, who fixed it for me to do more programming and less history, through to secondary-school teachers like Richard Furlong-Brown, who fixed it for me to do more programming and less rugby.

I must thank the mother of my children, Jutta, for her continued support, and the many people in my life, friends new and old, that keep me, roughly speaking, sane. Finally, a huge dollop of thanks must go to Aeron Buchanan, without whom the last five years of my life could never possibly have unfolded in the way they did and without whose time, support, and guidance this book would not be in as good shape as it is.


[[github_contrib]]
=== Contributions

Many contributors offered comments, corrections, and additions to the early-release draft on GitHub.

Contributions on GitHub were facilitated by two GitHub editors who volunteered to project manage, review, edit, merge, and approve pull requests and issues:

* Lead Github editor: Francisco Javier Rojas Garcia (fjrojasgarcia)
* Assisting Github editor: William Binns (wbnns)

Major contributions were provided on the topics of DApps, ENS, the EVM, fork history, gas, oracles, smart contract security, and Vyper. Additional contributions, which were not included in this first edition due to time and space constraints, can be found in the _contrib_ folder of the GitHub repository. Thousands of smaller contributions throughout the book have improved its quality, legibility, and accuracy. Sincere thanks to all those who contributed!

Following is an alphabetically sorted list of all the GitHub contributors, including their GitHub IDs in parentheses:

* Abhishek Shandilya (abhishandy)
* Adam Zaremba (zaremba)
* Adrian Li (adrianmcli)
* Adrian Manning (agemanning)
* Alejandro Santander (ajsantander)
* Alejo Salles (fiiiu)
* Alex Manuskin (amanusk)
* Alex Van de Sande (alexvandesande)
* Anthony Lusardi (pyskell)
* Assaf Yossifoff (assafy)
* Ben Kaufman (ben-kaufman)
* Bok Khoo (bokkypoobah)
* Brian Ethier (dbe)
* Bryant Eisenbach (fubuloubu)
* Chanan Sack (chanan-sack)
* Chris Remus (chris-remus)
* Christopher Gondek (christophergondek)
* Cornell Blockchain (CornellBlockchain)
  - Alex Frolov (sashafrolov)
  - Brian Guo (BrianGuo)
  - Brian Leffew (bleffew99)
  - Giancarlo Pacenza (GPacenza)
  - Lucas Switzer (LucasSwitz)
  - Ohad Koronyo (ohadh123)
  - Richard Sun (richardsfc)
* Cory Solovewicz (CorySolovewicz)
* Dan Shields (NukeManDan)
* Daniel Jiang (WizardOfAus)
* Daniel McClure (danielmcclure)
* Daniel Peterson (danrpts)
* Denis Milicevic (D-Nice)
* Dennis Zasnicoff (zasnicoff)
* Diego H. Gurpegui (diegogurpegui)
* Dimitris Tsapakidis (dimitris-t)
* Enrico Cambiaso (auino)
* Ersin Bayraktar (ersinbyrktr)
* Flash Sheridan (FlashSheridan)
* Franco Daniel Berdun (fMercury)
* Hon Lau (masterlook)
* Hudson Jameson (Souptacular)
* Iuri Matias (iurimatias)
* Ivan Molto (ivanmolto)
* Jacques Dafflon (jacquesd)
* Jason Hill (denifednu)
* Javier Rojas (fjrojasgarcia)
* Joel Gugger (guggerjoel)
* Jon Ramvi (ramvi)
* Jonathan Velando (rigzba21)
* Jules Lainé (fakje)
* Karolin Siebert (karolinkas)
* Kevin Carter (kcar1)
* Krzysztof Nowak (krzysztof)
* Lane Rettig (lrettig)
* Leo Arias (elopio)
* Liang Ma (liangma)
* Luke Schoen (ltfschoen)
* Marcelo Creimer (mcreimer)
* Martin Berger (drmartinberger)
* Masi Dawoud (mazewoods)
* Matthew Sedaghatfar (sedaghatfar)
* Michael Freeman (stefek99)
* Miguel Baizan (mbaiigl)
* Mike Pumphrey (bmmpxf)
* Mobin Hosseini (iNDicat0r)
* Nagesh Subrahmanyam (chainhead)
* Nichanan Kesonpat (nichanank)
* Nick Johnson (arachnid)
* Omar Boukli-Hacene (oboukli)
* Paulo Trezentos (paulotrezentos)
* Pet3rpan (pet3r-pan)
* Pierre-Jean Subervie (pjsub)
* Pong Cheecharern (Pongch)
* Qiao Wang (qiaowang26)
* Raul Andres Garcia (manilabay)
* Roger Häusermann (haurog)
* Solomon Victorino (bitsol)
* Steve Klise (sklise)
* Sylvain Tissier (SylTi)
* Taylor Masterson (tjmasterson)
* Tim Nugent (timnugent)
* Timothy McCallum (tpmccallum)
* Tomoya Ishizaki (zaq1tomo)
* Vignesh Karthikeyan (meshugah)
* Will Binns (wbnns)
* Xavier Lavayssière (xalava)
* Yash Bhutwala (yashbhutwala)
* Yeramin Santana (ysfdev)
* Zhen Wang (zmxv)
* ztz (zt2)


Without the help offered by everyone listed above, this book would not have been possible. Your contributions demonstrate the power of open source and open culture, and we are eternally grateful for your help. Thank you.

=== Sources

This book references various public and open-licensed sources:

https://github.com/ethereum/vyper/blob/master/README.md::
License: The MIT License (MIT)


https://vyper.readthedocs.io/en/latest/::
License: The MIT License (MIT)


https://solidity.readthedocs.io/en/v0.4.21/common-patterns.html::
License: The MIT License (MIT)

https://arxiv.org/pdf/1802.06038.pdf::
License: Arxiv Non-Exclusive-Distribution

https://github.com/ethereum/solidity/blob/release/docs/contracts.rst#inheritance::
License: The MIT License (MIT)

https://github.com/trailofbits/evm-opcodes::
License: Apache 2.0

https://github.com/ethereum/EIPs/::
License: Creative Commons CC0


https://blog.sigmaprime.io/solidity-security.html::
Licence: Creative Commons CC BY 4.0
