[preface]
[[preface]]
== Preface

////
TODO: add paragraph
////

[[writing_mastering_ethereum_sec]]
=== Writing Mastering Ethereum

////
TODO: add paragraph
////

[[intended_audience_sec]]
=== Intended audience

////
TODO: add paragraph
////

[[why_bees_sec]]
=== On the bees on this book's cover

The Western honey bee (Apis mellifera) is a species that exhibits highly complex behavior that, ultimately, benefits its hive. Each individual bee operates freely under a set of simple rules and communicate findings of importance by pheromones and waggle dance. This dance carries valuable information like the position of the sun and relative geographical coordinates from the hive to the target in question. By interpreting this dance, the bees can relay on this information or act on it, thus, carrying out the decentralized will of swarm intelligence.

Although bees form a caste-based society and have a queen for producing offspring, there is no central authority or leader in a beehive. The highly intelligent and sophisticated behavior exhibited by a multithousand-member colony is an emergent property that arises from the interaction of the individuals in a social network.

Nature demonstrates that decentralized systems can be resilient and can produce emergent complexity and incredible sophistication without the need for a central authority, hierarchy, or complex parts.

[[conventinons_used_sec]]
=== Conventions used in this book

((("typographical conventions")))The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or values determined by context.


[TIP]
====
This icon signifies a tip or suggestion.
====

[NOTE]
====
This icon signifies a general note.
====

[WARNING]
====
This icon indicates a warning or caution.
====

[[code_examples_sec]]
=== Code examples

((("code examples, obtaining and using")))The examples are illustrated in Solidity, JavaScript and Python, and using the command line of a Unix-like operating system. All code snippets are available in the GitHub repository in the https://github.com/ethereumbook/ethereumbook/tree/first_edition/code[_code_] subdirectory of the main repository. Fork the book code, try the code examples, or submit corrections via GitHub:

https://github.com/ethereumbook/ethereumbook/tree/first_edition/

All the code snippets can be replicated on most operating systems with a minimal installation of compilers, interpreters and libraries for the corresponding languages. Where necessary, we provide basic installation instructions and step-by-step examples of the output of those instructions.

Some of the code snippets and code output have been reformatted for print. In all such cases, the lines have been split by a backslash (\) character, followed by a newline character. When transcribing the examples, remove those two characters and join the lines again and you should see identical results as shown in the example.

All the code snippets use real values and calculations where possible, so that you can build from example to example and see the same results in any code you write to calculate the same values. For example, the private keys and corresponding public keys and addresses are all real. The sample transactions, contracts, blocks, and blockchain references have all been introduced in the actual Ethereum blockchain and are part of the public ledger, so you can review them on any Ethereum system.

[[using_code_examples_sec]]
=== Using code examples

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you're reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O'Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product's documentation does require permission.

((("attribution")))We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, ISBN, and copyright. For example: "_Mastering Ethereum_ by Andreas M. Antonopoulos and Gavin Wood (O'Reilly),
978-1-491-97194-9. Copyright 2018."

((("open source licenses")))Some editions of this book are offered under an open source license, such as https://creativecommons.org/licenses/by-nc/4.0/[CC-BY-NC], in which case the terms of that license apply.

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

[[ethereum_sddresses_and_transactions_sec]]
=== Ethereum addresses and transactions in this book

((("getting started", "warnings and cautions")))((("warnings and cautions", "avoid sending money to addresses appearing in book")))((("keys and addresses", "warnings and cautions")))((("transactions", "warnings and cautions")))((("blockchain applications", "warnings and cautions")))((("QR codes", "warnings and cautions")))The Ethereum addresses, transactions, keys, QR codes, and blockchain data used in this book are, for the most part, real. That means you can browse the blockchain, look at the transactions offered as examples, retrieve them with your own scripts or programs, etc.

However, note that the private keys used to construct the addresses printed in this book have been "burned". This means that if you send money to any of these addresses, the money will either be lost forever or will likely be taken since anyone who reads the book can take it using the private keys printed herein.

[WARNING]
====
DO NOT SEND MONEY TO ANY OF THE ADDRESSES IN THIS BOOK. Your money will be taken by another reader, or lost forever.
====

[[oreilly_safari_sec]]
=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (formerly Safari Books Online) is a membership-based training and reference platform for enterprise, government, educators, and individuals.
====

Members have access to thousands of books, training videos, Learning Paths, interactive tutorials, and curated playlists from over 250 publishers, including O'Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, and Course Technology, among others.

For more information, please visit pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em>http://oreilly.com/safari</em></a>].

[[how_to_contact_us_sec]]
=== How to contact us

((("comments and questions")))((("contact information")))Please address comments and questions concerning this book to the publisher:

++++
<ul class="simplelist">
  <li>O'Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (in the United States or Canada)</li>
  <li>707-829-0515 (international or local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

Send comments or technical questions about this book to pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

For more information about our books, courses, conferences, and news, see our website at link:$$https://www.oreilly.com$$[].

Find us on Facebook: link:$$https://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$https://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$https://www.youtube.com/oreillymedia$$[]

[[contacting_the_authour_sec]]
=== Contacting the authors

Information about _Mastering Ethereum_ as well as the Open Edition and translations are available on:
link:$$https://ethereumbook.info/$$[]

==== Contacting Andreas

You can contact Andreas M. Antonopoulos on his personal site:
link:$$https://antonopoulos.com/$$[]

Subscribe to Andreas's channel on YouTube:
link:$$https://www.youtube.com/aantonop$$[]

Like Andreas's page on Facebook:
link:$$https://www.facebook.com/AndreasMAntonopoulos$$[]

Follow Andreas on Twitter:
link:$$https://twitter.com/aantonop$$[]

Connect with Andreas on LinkedIn:
link:$$https://linkedin.com/company/aantonop$$[]

Andreas would also like to thank all of the patrons who support his work through monthly donations. You can support Andreas on Patreon at:
link:$$https://patreon.com/aantonop$$[]


==== Contacting Gavin

////
TODO:
////

[[acknowledgments_sec]]
=== Acknowledgments by Andreas

////
TODO:
////

I owe my love of words and books to my mother, Theresa, who raised me in a house with books lining every wall. My mother also bought me my first computer in 1982, despite being a self-described technophobe. My father, Menelaos, a civil engineer who published his first book at 80 years old, was the one who taught me logical and analytical thinking and a love of science and engineering.

Thank you all for supporting me throughout this journey.

=== Acknowledgments by Gavin

////
TODO:
////

[[github_contrib]]
=== Contributions

Many contributors offered comments, corrections, and additions to the early-release draft on GitHub.

Contributions on GitHub were facilitated by two GitHub editors who volunteered to project manage, review, edit, merge and approve pull requests and issues:

* Lead Github Editor: Francisco Javier Rojas Garcia (fjrojasgarcia)
* Assisting Github Editor: William Binns (wbnns)

Major contributions were provided in the chapters on DApps, ENS, Fork History, Gas, EVM, Oracles, Smart Contract Security and Vyper. Additional contributions, which were not included in the first edition due to time and space constraints can be found in the +contrib+ folder on the GitHub repository. Thousands of smaller contributions were provided throughout the book, improving the quality, legibility and accuracy of the book. Sincere thanks to all those who contributed!

Following is an alphabetically sorted list of all GitHub contributors, including their GitHub ID in parentheses:

* Abhishek Shandilya (abhishandy)
* Adam Zaremba (zaremba)
* Adrian Li (adrianmcli)
* Adrian Manning (agemanning)
* Alejandro Santander (ajsantander)
* Alejo Salles (fiiiu)
* Alex Manuskin (amanusk)
* Alex Van de Sande (alexvandesande)
* Anthony Lusardi (pyskell)
* Assaf Yossifoff (assafy)
* Ben Kaufman (ben-kaufman)
* Bok Khoo (bokkypoobah)
* Brian Ethier (dbe)
* Bryant Eisenbach (fubuloubu)
* Chanan Sack (chanan-sack)
* Christopher Gondek (christophergondek)
* Chris Remus (chris-remus)
* Cornell Blockchain (CornellBlockchain)
  - Alex Frolov (sashafrolov)
  - Brian Guo (BrianGuo)
  - Brian Leffew (bleffew99)
  - Giancarlo Pacenza (GPacenza)
  - Lucas Switzer (LucasSwitz)
  - Ohad Koronyo (ohadh123)
  - Richard Sun (richardsfc)
* Cory Solovewicz (CorySolovewicz)
* Dan Shields (NukeManDan)
* Daniel Jiang (WizardOfAus)
* Daniel McClure (danielmcclure)
* Daniel Peterson (danrpts)
* Denis Milicevic (D-Nice)
* Dennis Zasnicoff (zasnicoff)
* Diego H. Gurpegui (diegogurpegui)
* Dimitris Tsapakidis (dimitris-t)
* Enrico Cambiaso (auino)
* Flash Sheridan (FlashSheridan)
* Franco Daniel Berdun (fMercury)
* Hon Lau (masterlook)
* Hudson Jameson (Souptacular)
* Iuri Matias (iurimatias)
* Ivan Molto (ivanmolto)
* Jacques Dafflon (jacquesd)
* Jason Hill (denifednu)
* Javier Rojas (fjrojasgarcia)
* Joel Gugger (guggerjoel)
* Jonathan Velando (rigzba21)
* Jon Ramvi (ramvi)
* Jules Lainé (fakje)
* Kevin Carter (kcar1)
* Krzysztof Nowak (krzysztof)
* Lane Rettig (lrettig)
* Leo Arias (elopio)
* Luke Schoen (ltfschoen)
* Liang Ma (liangma)
* Marcelo Creimer (mcreimer)
* Martin Berger (drmartinberger)
* Masi Dawoud (mazewoods)
* Matthew Sedaghatfar (sedaghatfar)
* Michael Freeman (stefek99)
* Mike Pumphrey (bmmpxf)
* Mobin Hosseini (iNDicat0r)
* Nagesh Subrahmanyam (chainhead)
* Nichanan Kesonpat (nichanank)
* Nick Johnson (arachnid)
* Omar Boukli-Hacene (oboukli)
* Paulo Trezentos (paulotrezentos)
* Pet3rpan (pet3r-pan)
* Pierre-Jean Subervie (pjsub)
* Pong Cheecharern (Pongch)
* Qiao Wang (qiaowang26)
* Raul Andres Garcia (manilabay)
* Roger Häusermann (haurog)
* Solomon Victorino (bitsol)
* Steve Klise (sklise)
* Sylvain Tissier (SylTi)
* Taylor Masterson (tjmasterson)
* Tim Nugent (timnugent)
* Timothy McCallum (tpmccallum)
* Tomoya Ishizaki (zaq1tomo)
* Vignesh Karthikeyan (meshugah)
* Will Binns (wbnns)
* Xavier Lavayssière (xalava)
* Yash Bhutwala (yashbhutwala)
* Yeramin Santana (ysfdev)
* Zhen Wang (zmxv)
* ztz (zt2)


Without the help offered by everyone listed above, this book would not have been possible. Your contributions demonstrate the power of open source and open culture, and we are eternally grateful for your help. Thank you.

=== Sources

Some of the content of this book references or sources various public and open-licensed sources:

https://github.com/ethereum/vyper/blob/master/README.md

License: The MIT License (MIT)


http://vyper.readthedocs.io/en/latest/

License: The MIT License (MIT)


http://solidity.readthedocs.io/en/v0.4.21/common-patterns.html

License: The MIT License (MIT)


https://arxiv.org/pdf/1802.06038.pdf

License: Arxiv Non-Exclusive-Distribution


https://github.com/ethereum/solidity/blob/release/docs/contracts.rst#inheritance

License: The MIT License (MIT)


https://github.com/trailofbits/evm-opcodes

License: Apache 2.0


https://github.com/ethereum/EIPs/

License: Creative Commons CC0


https://blog.sigmaprime.io/solidity-security.html

Licence: Creative Commons CC BY 4.0
