== Smart Contracts

=== What is a Smart Contract?

A Smart Contract is a computer logic that, given certain conditions, can enforce the execution of one or more transactions in an irreversible and decentralized way without the need for third parties. The term was first used by Nick Szabo in 1994.

Bitcoin supports smart contracts in a limited way by _Turing incomplete_ Script language. On the other hand, the Ethereum blockchain uses a Turing complete virtual machine (the EVM) which makes the Smart Contracts essentially programs that run in a distributed way. In that sense, they are pieces of code that live on the blockchain and are executed when a corresponding transaction is sent and processed. They can read other contracts' data (if that second contract is designed for it), make decisions, send ether and execute other contracts' functions. Smart Contracts will exist and have the ability to run as long as the whole network exists, and will only stop if they run out of _gas_ or if they were programmed to self destruct.

It is important to state that a Smart Contract is composed by different functions, and those functions will only be executed if triggered by a transaction for that purpose. Also, is relevant to mention that even if a contract's function can call another contract's function, the entire chain of execution has to start with a transaction signed by an EOA.

[[high_level_languages]]
=== Introduction to Ethereum High-Level Languages

The Ethereum Virtual Machine is an emulated computer that runs a special form of _machine code_ called _bytecode_, just like your computer's CPU which also runs machine code. While it is possible to program the EVM directly in bytecode, it's unwieldy and very difficult for programmers to read, understand, and collaborate in a low-level language like bytecode. Instead, we use a high-level symbolic language to write our program and a compiler to convert it into bytecode.

Ethereum has several high-level languages, with the compilers needed to produce EVM-executable bytecode, including (ordered by approximate age):

LLL:: A functional (declarative) programming language, with Lisp-like syntax. It was the first high-level language for Ethereum smart contracts, but it is rarely used.

Serpent:: A procedural (imperative) programming language with syntax similar to Python. Can also be used to write functional (declarative) code, though it is not entirely free of side-effects. Used sparsely. First created by Vitalik Buterin.

Solidity:: A procedural (imperative) programming language with syntax that is similar to JavaScript, C++ or Java. The most popular and most frequently used language for Ethereum smart contracts. First created by Gavin Wood (co-author of this book)

Vyper:: A more recently developed language, similar to Serpent and with Python-like syntax. Intended to get closer to a pure-functional Python-like language than Serpent, but not to replace Serpent. First created by Vitalik Buterin.

Bamboo:: A newly developed language, influenced by Erlang with explicit state transitions and without iterative flows (loops). Intended to reduce side-effects and increase auditability. Very new and rarely used.

As you can see, there many languages to choose from. However, of all these Solidity is by far the most popular, to the point of being the de-facto high-level language of Ethereum and even other EVM-like blockchains. We will spend most of our time using Solidity, but will also explore some of the examples in other high-level languages, to gain an understanding of their different philosophies.

=== Building a Smart Contract

[[testing_frameworks]]
=== Testing Smart Contracts


Seeing as most smart contract languages don't have simple print statements or ways of writing out to files (since such constructs don't exist on the real Ethereum network,) smart contracts can be tested via deployment to the real Ethereum network, deployment to a testnet, or using an Ethereum network simulator locally. Testnets (covered previously) are helpful, but the most rich testing can be done on local network simulators with frameworks. 


==== Testing Frameworks 
There are several commonly-used test frameworks (no particular order):
Truffle Test:: Part of the Truffle framework, Truffle allows for unit tests to be written in Javascript (Mocha based) or Solidity. These tests are run against TestRPC/Ganache.

Embark Framework Testing:: Embark integrates with Mocha to run unit tests written in Javascript. The tests are in turn run against contracts deployed on TestRPC/Ganache.

Dapp:: Dapp uses native Solidity code (a library called ds-test) and a Parity built Rust library called Ethrun to execute Ethereum byte code and then assert correctness.

Populus:: Populus uses python and its own chain emulator to run contracts written in solidity. Unit tests are written in Python with the pytest library.

////TO DO: A comparison of the features/abilities of each one. Did I miss any?

===== TestRPC/Ganache
TestRPC/Ganache is a simulator that runs smart contracts on a small private blockchain. Both are names for the same project. Ganache can provide a rich GUI with information about every account, blockchain logs, and others, while there is also a normal, CLI version. 

==== On-Blockchain Testing
Although most testing shouldn't occur on deployed contracts, a contract's behavior can be checked via Ethereum clients.  

///TODO: this would have a few commands along the lines of eth.getCode(contractaddress) to explain geth commands to verify correct execution.

=== Ethereum Contract ABI
In computer software, an application binary interface (ABI) is an interface between two program modules; often, one at the level of machine code, and the other at the level of a program run by a user. An ABI defines how data structures or computational routines are accessed in *machine code*; this is not to be confused with an API, which defines this access in high-level, often human-readable format as *source code*. The ABI is thus the de facto method for encoding and decoding data into and out of machine code.

In Ethereum, the ABI is used to encode contract calls for the EVM, as well as to read data out of transactions.
As discussed in a previous section, an Ethereum smart contract is bytecode deployed on the blockchain under a contract address. The purpose of an ABI is to thus specify which functions in the contract to invoke and to get a guarantee that the function will return data in expected format. 

____
An account wishing to use a smart contract's function uses the ABI to hash the function definition so it can create the EVM bytecode required to call the function. This is then included in the data field of a transaction and interpreted by the EVM with the code at the target account (the address of the contract).
____

The JSON format for a contract's ABI is given by an array of function and event descriptions. A function description is a JSON object with fields for `type`, `name`, `inputs`, `outputs`, `constant`, and `payable`. An event description object has fields for `type`, `name`, `inputs`, and `anonymous`. 

The ABI thus specifies information about functions in a smart contract, relaying information such as inputs and types. However, the ABI *only* contains information about functions and events, meaning it will not hold values for fields such as state variables or modifiers.

If a web application wants to interact with a published contract, it needs the contract address and its Ethereum ABI.

==== Structure of Call Data
The data for a function call is a concatenation of several values of bytes. We discuss these in steps below.

*First Four Bytes*: The call data always begins with *four bytes* of the function signature. In specific, these are the first four bytes of the Keccak-256 hash of the *signature* of a function. In this context, the signature is simply the function name with a parenthesised list of parameter types split by a single comma. 

Assume, as our running example, the brief contract `Test`: 

[source,solidity]
contract Test {
  function foo(uint32 u, bool b) returns (bool b) { u > 2000 && b; }
}

.To encode function `foo(uint32 u, bool b)`:
* The signature of `foo(uint32 u, bool b)` would be `foo(uint32,bool)`
* Running `foo(uint32,bool)` through Keccak-256 outputs the hash `cc822237a37f9290b70dab4d640156d816bf8abdb959b5971d803a639dadef98`
* The first four bytes of the hash are `cc822237`, which brings us to a Method ID of `0xcc822237`

*5th Byte And On*: We continue our data by encoding the *arguments* of our function. Encoding a `uint32` means converting the number to hexadecimal form and padding it with 0's until it becomes 32 bytes long, while encoding a `bool` is equivalent to encoding a `uint` with values `1` for `true` and `0` for `false`. A full list of type encoding can be found at the link attached in the _Further Reading_ section.

.To continue with our example above, we call our function `foo` with parameters `2345` and `true`:
* The hexadecimal representation of `2345` is `0x929`, and so padded to 32 bytes the first argument `u` is encoded as `0x0000000000000000000000000000000000000000000000000000000000000929`
* The hexadecimal representation of `true` is `1`, and so padded to 32 bytes the second argument `b` becomes `0x0000000000000000000000000000000000000000000000000000000000000001`

*Result*: We concatenate the Method ID with our encoded arguments to reach the finished call data for our function call. In our case, the call data for function `foo(uint32 u, bool b)` with arguments `2345` and `true` is
`0xcc82223700000000000000000000000000000000000000000000000000000000000009290000000000000000000000000000000000000000000000000000000000000001`

____
We notice that our function returns a single `bool` value. For our choices of `u` and `b`, `foo` returns `true`, which would be the single byte array `0x0000000000000000000000000000000000000000000000000000000000000000`.
____

....
==== Example (Maybe delete this section):

Given the contract:

[source,solidity]
contract Example {
  function greater2000(uint32 x, uint32 y) returns (bool b) { x+y > 2000; }
}

.Our contract above contains a single function, `greater2000`, which simply determines whether the sum of its two integer inputs is greater than the integer 2000. Assume we call `greater2000` with parameters `1150` and `763`. In this case, we would pass 68 bytes in total, broken down into: 
* `0x25f611fb`: the Method ID, derived as the first four bytes of the Keccak-256 hash of the signature `greater20(uint32,uint32)`
* `0x000000000000000000000000000000000000000000000000000000000000047E`: the first parameter `x`, the uint32 value `1150` padded to 32 bytes
* `0x00000000000000000000000000000000000000000000000000000000000002FB`: the second parameter `y`, the uint32 value `763` padded to 32 bytes

In total: 

`0x25f611fb000000000000000000000000000000000000000000000000000000000000047E00000000000000000000000000000000000000000000000000000000000002FB`

We notice that this function returns a single `bool`. For this choice of `x` and `y`, `greater2000` returns `false`, which would be the single byte array `0x0000000000000000000000000000000000000000000000000000000000000000`.
....

//TO-DO: Discuss Events vs. Functions

==== Further Reading
The Application Binary Interface (ABI) is strongly typed, known at compilation time and static. All contracts have the interface definitions of any contracts the intend to call available at compile-time. Formal specification of the encoding 

A more rigorous and in-depth explanation of the Ethereum ABI can be found at 
`https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI`. The link includes details about the formal specification of encoding and various helpful examples.

=== Deploying Smart Contracts

=== Best Practices

==== Development Style

==== Design Patterns

==== Modularity and Side Effects

==== Contract Libraries

Github link; https://github.com/ethpm

Repository link; https://www.ethpm.com/registry

Website; https://www.ethpm.com/

Documentation; https://www.ethpm.com/docs/integration-guide

==== Security Best Practices

Github: https://github.com/ConsenSys/smart-contract-best-practices/

Docs: https://consensys.github.io/smart-contract-best-practices/

https://blog.zeppelin.solutions/onward-with-ethereum-smart-contract-security-97a827e47702

https://openzeppelin.org/

https://github.com/OpenZeppelin/zeppelin-solidity

https://medium.com/zeppelin-blog/the-hitchhikers-guide-to-smart-contracts-in-ethereum-848f08001f05#.cox40d2ut
