== Tokens

=== What are tokens?

The word _token_ derives from the Old English "tacen" meaning a sign or symbol. Commonly used to mean privately-issued coin-like items that have insignificant value, as used in transportation tokens, laundry tokens, arcade tokens. Nowadays, tokens based on blockchains are redefining the word to mean cryptographic abstractions that can be owned and represent assets, currency, or access rights.

In this section we look at Ethereum tokens and the standards and technologies that they are based on. We also look at how they are created, traded and their various uses.

=== Tokens and Fungibility

From Wikipedia:

 In economics, fungibility is the property of a good or a commodity whose individual units are essentially interchangeable.

Tokens are fungible when we can substitute any single unit of the token for another without any difference in its value or function. For example, ether is a fungible token, as any unit of ether has the same value and use as any other unit of ether.

Strictly speaking, if a token's historical provenance can be tracked, then it is not entirely fungible. The ability to track provenance can lead to blacklisting and whitelisting, reducing or eliminating fungibility. We will examine this further in <<privacy>>.

Non-fungible tokens are tokens that each represent a unique tangible or intangible item and therefore are not interchangeable. For example, a token that represents ownership of a _specific_ Van Gogh painting is not equivalent to another token that represents a Picasso. Similarly, a token representing a _specific_ digital (intangible) collectible is not fungible.

We will see examples of both fungible and non-fungible tokens later in this section.

=== Tokens and Tangibility

Tokens are abstractions that represent something. They can be intangible, such as a digital resource (ether, the ability to buy gas), a voting share for the Tesla corporation, or a certificate of academic achievement.

Tokens can also represent ownership of a tangible good or asset, such as a real-estate property, a bar of gold.

Ethereum tokens are used to represent ownership of both tangible and intangible assets. Sometimes, it is hard to discern if the token represents a tangible asset or an intangible, such as "access" to a tangible asset. For example, if you have a token that opens the door to an Airbnb apartment rental for one week, is that tangible (the apartment), or intangible (the rental contract).

=== Tokens and Intrinsicality

Some tokens represent intangibles (digital items) that are _intrinsic_ to the blockchain where the token is used. Those digital intangibles are governed by consensus rules, just like the tokens. This has an important implication: tokens that represent intrinsic intangibles do not carry counterparty risk. If you own 1 ether, there is no counterparty risk.

Conversely, many tokens are used to represent _extrinsic_ things, like real-estate, corporate voting shares, gold bars. The rules and ownership of these items, which are not "on" the blockchain are governed by law, custom and policy that are separate from the consensus rules that govern the token. As a result, these extrinsic assets carry countrparty risk because they are held by custodians or controlled by laws and policies outside the blockchain environment.

One of the most important ramifications of blockchain-based tokens is the ability to change extrinsic intangibles into intrinsic intangibles and thereby remove counterparty risk. A good example is moving from equity in a corporation (extrinsic) to a equity or voting token in a _decentralized autonomous organization_ or similar (intrinsic) organization. A token to a DAO does not carry counterparty risk, if the DAOs operation and the blockchain's governance is truly autonomous.

=== How are tokens used?

The most obvious use of tokens is as digital private currencies. However, this is only one possible use. Tokens can be programmed to serve many different functions, often overlapping. For example, a token can simultaneously convey a voting right, an access right and ownership of a resource. Currency is just the first "app".

Currency:: A token can serve as a form of currency, with a value determined through private trade. For example, ether or bitcoin.

Resource:: A token can represent a resource earned or produced in a sharing-economy or resource-sharing environment. For example, a storage or CPU token representing resources that can be shared over a network.

Asset:: A token can represent ownership of an intrinsic or extrinsic, tangible or intangible asset. For example, gold, real-estate, a car, oil, energy etc.

Access:: A token can represent access rights and even convey access to a digital or physical property, such as a discussion forum, an exclusive website, a hotel room, a rental car.

Equity:: A token can represent shareholder equity in a digital organization (e.g. a DAO) or legal fiction (e.g. a corporation)

Voting:: A token can represent voting rights in a digital or legal system.

Collectible:: A token can represent a digital (e.g. CryptoPunks) or physical collectible (e.g. a painting)

Identity:: A token can represent a digital (e.g. avatar) or legal identity (e.g. national ID)

Attestation:: A token can represent a certification or attestation of fact by some authority or by a decentralized reputation system.

Often, a single token has several of these functions overlayed. In some cases it is hard to discern between them, as the physical equivalents have always been inextricably linked. For example, in the physical world, a driver's license (attestation) is also an identity document (identity) and the two cannot be separated. In the digital realm, previously commingled functions can be separated and developed independently (e.g. an anonymous attestation).

=== Token Standards

==== ERC20

https://github.com/ethereum/EIPs/issues/20

ERC20 is a standard for fungible tokens. Fungibility refers to the property that different units of the token are interchangeable. For example, 0x is a ERC20 token. Each unit of a 0x token can be interchangeably used to pay for using decentralized exchanges built on the 0x protocol.

===== Problems with ERC20

Both ERC223 and ERC777 standards are proposals that attempt to address isues with the ERC20 standard.

==== ERC223

https://github.com/ethereum/EIPs/issues/223

==== ERC777

https://github.com/ethereum/EIPs/issues/777

==== ERC721

https://github.com/ethereum/EIPs/issues/721

ERC721 is a standard for non-fungible tokens. For example, CryptoKitty is a ERC721 token. Each unit of the token represents a virtual cat with a unique set of characteristics.

https://www.reddit.com/r/ethereum/comments/7qjw6x/everything_you_need_to_know_about_erc777_the_new/

=== Tokens and ICOs
