
== What is Ethereum?

Ethereum is a globally decentralized computing platform that executes programs called _smart contracts_ using a blockchain to synchronize and store the system _state_ and a crypto-currency called _ether_ to meter and constrain execution resource cost.

=== Compared to bitcoin
Why not bitcoin? A stack based language that is Turing incomplete is not flexible/expressive enough to build varies apps, only narrow domain specific apps that relate to currency transactions.

Ehtereum as general purpose blockchain to build apps on. Compare to summer of 2014 - a chain for every app. Devlopers have to worry about the platform basics rther than focus on their application. Same as early years of computing. By having a common standard, flexible platform, developers can build their app and not worry about the platform details (too much, ideally)

=== How Ethereum solves this

High level, expressive flexible language that abstracts the details of the security model, the blockchain mechanism, the consensus algorithm.


=== Smart contracts

What are smart contracts? Neither contracts nor smart. PROGRAMS.

Programmers perspective - what is diff about Ethereum

it offers a programing language, development frameworks and execution platform that are very familiar. Solidity modeled after javascript (??), strong javascript integration, common scaffold patterns (truffle), in browser DOM, tight integrations with popular UI/UX frameworks.

Double edged sword - language appears simple and aims to abstract the platforms security consideration. In practice, writing secure code in this language is very difficult and requires awareness of security design patterns involving conncurrency, re-entrancy and distributed systems. Moves quickly and is not well understood. False sense of security leads to losses.

==== Solidity

==== Other high-level languages

====  EVM bytecode.

Relationship to high level languages

=== Dev culture
Culture is innovate quickly, break things.


=== Why learn Ethereum

==== Learning about blockchains more generally

==== Cross discipline skills: Crypto, Distrib Systems, Blockchains, Compilers, security

==== Fit into a broader team of developers

UX, Devops, Systems, Network, Security and.. you!


=== What this book will teach you

What does this book contain:

How Ethereum works
How to program using Ethereum as a platform.

From a simple contract, all the way down to how it runs in the EVM, and then back up again.

=== What you need to know

Not necessary to understand Javascript. Programming experience will be very helpful, but is not necessarily required to understand some of these concepts
